In [1]:
import pandas as pd
import uuid

In [2]:
df = pd.read_parquet('../parquet_output/events_pageview_identifier.parquet')
df.head()

,event_date,event_timestamp,session_id,pageview_id,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,...,session_traffic_source_last_click_google_ads_campaign_campaign_id,session_traffic_source_last_click_google_ads_campaign_campaign_name,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id
0,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,first_visit,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,None,NaN,None,2024,11,None,None
1,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,session_start,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,None,NaN,None,2024,11,None,None
2,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,page_view,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,None,NaN,None,2024,11,None,None
3,20241113,2024-11-14 05:54:57.126554,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,user_session_info,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,None,NaN,None,2024,11,_1731563690,_251617.1731563690
4,20241113,2024-11-14 05:55:08.384203,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,scroll,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,None,NaN,None,2024,11,None,None

In [3]:
keys = (
    df["session_id"].astype(str) + "_" +
    df["pageview_id"].astype(str) + "_" +
    df["event_name"].astype(str) + "_" +
    df["event_timestamp"].astype(str)
)

df["event_id"] = [str(uuid.uuid5(uuid.NAMESPACE_DNS, k)) for k in keys]

In [4]:
df

,event_date,event_timestamp,session_id,pageview_id,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,...,session_traffic_source_last_click_google_ads_campaign_campaign_name,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id,event_id
0,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,first_visit,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,ca6c0d15-cff3-5e24-acf1-32a16e437eca
1,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,session_start,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,1d876485-58fe-50bc-9d35-d49102b5929f
2,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,page_view,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,ba318429-35c6-5e9b-97cf-5af73f23a361
3,20241113,2024-11-14 05:54:57.126554,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,user_session_info,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,NaN,None,2024,11,_1731563690,_251617.1731563690,30ef06d6-1cd0-508b-8cdc-b779fe8d33e6
4,20241113,2024-11-14 05:55:08.384203,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,scroll,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,7520f636-f1aa-5704-a018-8f352bf5ed34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260859,20241113,2024-11-14 03:17:08.166826,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,...,None,None,None,NaN,None,2024,11,_1731554221,_2145680768.1731554221,b3442476-472f-5b31-b138-decd75dc9029
260860,20241113,2024-11-14 03:17:26.457025,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,f09b9137-56cb-5308-9ef7-0a6ea93884ee
260861,20241113,2024-11-14 03:17:26.457025,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,f09b9137-56cb-5308-9ef7-0a6ea93884ee
260862,20241113,2024-11-14 03:17:45.807694,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,cc8a8d6a-c437-5afe-8004-e240e592fda1
260863,20241113,2024-11-14 03:19:56.763039,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,user_engagement,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,95d57de2-cae7-58d9-93cb-1e771ac0aca7

In [5]:
cols = list(df.columns)

desired_order =['event_date','event_timestamp','session_id','pageview_id','event_name','event_id']
new_order = desired_order + [c for c in cols if c not in desired_order]
df = df[new_order]
df

,event_date,event_timestamp,session_id,pageview_id,event_name,event_id,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,...,session_traffic_source_last_click_google_ads_campaign_campaign_id,session_traffic_source_last_click_google_ads_campaign_campaign_name,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id
0,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,first_visit,ca6c0d15-cff3-5e24-acf1-32a16e437eca,1731563683537,None,https://www.shopko.com/,1.0,...,None,None,None,None,NaN,None,2024,11,None,None
1,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,session_start,1d876485-58fe-50bc-9d35-d49102b5929f,1731563683537,None,https://www.shopko.com/,1.0,...,None,None,None,None,NaN,None,2024,11,None,None
2,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,page_view,ba318429-35c6-5e9b-97cf-5af73f23a361,1731563683537,None,https://www.shopko.com/,1.0,...,None,None,None,None,NaN,None,2024,11,None,None
3,20241113,2024-11-14 05:54:57.126554,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,user_session_info,30ef06d6-1cd0-508b-8cdc-b779fe8d33e6,1731563683537,None,https://www.shopko.com/,1.0,...,None,None,None,None,NaN,None,2024,11,_1731563690,_251617.1731563690
4,20241113,2024-11-14 05:55:08.384203,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,scroll,7520f636-f1aa-5704-a018-8f352bf5ed34,1731563683537,None,https://www.shopko.com/,1.0,...,None,None,None,None,NaN,None,2024,11,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260859,20241113,2024-11-14 03:17:08.166826,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,scroll,b3442476-472f-5b31-b138-decd75dc9029,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,...,None,None,None,None,NaN,None,2024,11,_1731554221,_2145680768.1731554221
260860,20241113,2024-11-14 03:17:26.457025,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,scroll,f09b9137-56cb-5308-9ef7-0a6ea93884ee,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,...,None,None,None,None,NaN,None,2024,11,None,None
260861,20241113,2024-11-14 03:17:26.457025,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,scroll,f09b9137-56cb-5308-9ef7-0a6ea93884ee,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,...,None,None,None,None,NaN,None,2024,11,None,None
260862,20241113,2024-11-14 03:17:45.807694,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,scroll,cc8a8d6a-c437-5afe-8004-e240e592fda1,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,...,None,None,None,None,NaN,None,2024,11,None,None
260863,20241113,2024-11-14 03:19:56.763039,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,user_engagement,95d57de2-cae7-58d9-93cb-1e771ac0aca7,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,...,None,None,None,None,NaN,None,2024,11,None,None

In [6]:
df.to_parquet('../parquet_output/events_event_identifier.parquet')