In [1]:
import pandas as pd
import uuid

In [6]:
df = pd.read_parquet('../parquet_output/events_session_identifier.parquet')
df

,event_date,event_timestamp,session_id,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,ep_batch_ordering_id,...,session_traffic_source_last_click_google_ads_campaign_campaign_id,session_traffic_source_last_click_google_ads_campaign_campaign_name,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id
0,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,first_visit,1731563683537,None,https://www.shopko.com/,1.0,None,1,...,None,None,None,None,NaN,None,2024,11,None,None
1,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,session_start,1731563683537,None,https://www.shopko.com/,1.0,None,1,...,None,None,None,None,NaN,None,2024,11,None,None
2,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,page_view,1731563683537,None,https://www.shopko.com/,1.0,None,1,...,None,None,None,None,NaN,None,2024,11,None,None
3,20241113,2024-11-14 05:54:57.126554,56b4c156-3b3b-449f-8db0-18dfb3936d53,user_session_info,1731563683537,None,https://www.shopko.com/,1.0,None,2,...,None,None,None,None,NaN,None,2024,11,_1731563690,_251617.1731563690
4,20241113,2024-11-14 05:55:08.384203,56b4c156-3b3b-449f-8db0-18dfb3936d53,scroll,1731563683537,None,https://www.shopko.com/,1.0,None,3,...,None,None,None,None,NaN,None,2024,11,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260859,20241113,2024-11-14 03:17:08.166826,df966189-a01b-4b3c-abe7-7d6b5481a98c,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,2,...,None,None,None,None,NaN,None,2024,11,_1731554221,_2145680768.1731554221
260860,20241113,2024-11-14 03:17:26.457025,df966189-a01b-4b3c-abe7-7d6b5481a98c,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,...,None,None,None,None,NaN,None,2024,11,None,None
260861,20241113,2024-11-14 03:17:26.457025,df966189-a01b-4b3c-abe7-7d6b5481a98c,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,...,None,None,None,None,NaN,None,2024,11,None,None
260862,20241113,2024-11-14 03:17:45.807694,df966189-a01b-4b3c-abe7-7d6b5481a98c,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,4,...,None,None,None,None,NaN,None,2024,11,None,None
260863,20241113,2024-11-14 03:19:56.763039,df966189-a01b-4b3c-abe7-7d6b5481a98c,user_engagement,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,5,...,None,None,None,None,NaN,None,2024,11,None,None

In [3]:
import pandas as pd
from typing import List, Optional, Union

def reorder_columns(
    df: pd.DataFrame,
    desired_order: Optional[List[str]] = None,
    insert_after: Optional[Union[str, List[str]]] = None,
    target_col: Optional[str] = None
) -> pd.DataFrame:
    """
    Reorder DataFrame columns efficiently.

    Parameters
    ----------
    df : pd.DataFrame
    desired_order : list of str, optional
        Columns to appear first; others follow in original order.
    insert_after : str or list of str, optional
        Column(s) to move immediately after target_col.
    target_col : str, optional
        The column after which insert_after columns will be placed.

    Returns
    -------
    pd.DataFrame
        DataFrame with reordered columns.
    """
    cols = list(df.columns)

    # Apply desired order
    if desired_order:
        first_cols = [c for c in desired_order if c in cols]
        remaining_cols = [c for c in cols if c not in first_cols]
        cols = first_cols + remaining_cols

    # Apply insert_after for one or multiple columns
    if insert_after and target_col:
        if isinstance(insert_after, str):
            insert_after = [insert_after]
        insert_after = [c for c in insert_after if c in cols and target_col in cols]

        # Remove and insert each column in order
        for c in insert_after:
            cols.insert(cols.index(target_col) + 1, cols.pop(cols.index(c)))
            target_col = c  # Update target for sequential insertion

    return df[cols]

In [4]:
df = reorder_columns(df, insert_after="session_id", target_col="user_prop_user_client_id")

In [9]:
desired_order = ["event_date", "event_timestamp", "session_id"]
df1 = reorder_columns(df, desired_order=desired_order)

In [12]:
df1

,event_date,event_timestamp,session_id,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,ep_batch_ordering_id,...,session_traffic_source_last_click_google_ads_campaign_campaign_name,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id,ep_ga_session_number
0,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,first_visit,1731563683537,None,https://www.shopko.com/,1.0,None,1,...,None,None,None,NaN,None,2024,11,None,None,1
1,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,session_start,1731563683537,None,https://www.shopko.com/,1.0,None,1,...,None,None,None,NaN,None,2024,11,None,None,1
2,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,page_view,1731563683537,None,https://www.shopko.com/,1.0,None,1,...,None,None,None,NaN,None,2024,11,None,None,1
3,20241113,2024-11-14 05:54:57.126554,56b4c156-3b3b-449f-8db0-18dfb3936d53,user_session_info,1731563683537,None,https://www.shopko.com/,1.0,None,2,...,None,None,None,NaN,None,2024,11,_1731563690,_251617.1731563690,1
4,20241113,2024-11-14 05:55:08.384203,56b4c156-3b3b-449f-8db0-18dfb3936d53,scroll,1731563683537,None,https://www.shopko.com/,1.0,None,3,...,None,None,None,NaN,None,2024,11,None,None,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260859,20241113,2024-11-14 03:17:08.166826,df966189-a01b-4b3c-abe7-7d6b5481a98c,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,2,...,None,None,None,NaN,None,2024,11,_1731554221,_2145680768.1731554221,1
260860,20241113,2024-11-14 03:17:26.457025,df966189-a01b-4b3c-abe7-7d6b5481a98c,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,...,None,None,None,NaN,None,2024,11,None,None,1
260861,20241113,2024-11-14 03:17:26.457025,df966189-a01b-4b3c-abe7-7d6b5481a98c,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,...,None,None,None,NaN,None,2024,11,None,None,1
260862,20241113,2024-11-14 03:17:45.807694,df966189-a01b-4b3c-abe7-7d6b5481a98c,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,4,...,None,None,None,NaN,None,2024,11,None,None,1
260863,20241113,2024-11-14 03:19:56.763039,df966189-a01b-4b3c-abe7-7d6b5481a98c,user_engagement,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,5,...,None,None,None,NaN,None,2024,11,None,None,1

In [17]:
df3 = reorder_columns(
    df,
    desired_order=["event_date", "event_timestamp","event_name"],
    insert_after=["session_id", "ep_ga_session_number"],
    target_col="event_name"
)

In [18]:
df3

,event_date,event_timestamp,event_name,session_id,ep_ga_session_number,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,...,session_traffic_source_last_click_google_ads_campaign_campaign_id,session_traffic_source_last_click_google_ads_campaign_campaign_name,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id
0,20241113,2024-11-14 05:54:51.907376,first_visit,56b4c156-3b3b-449f-8db0-18dfb3936d53,1,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,None,NaN,None,2024,11,None,None
1,20241113,2024-11-14 05:54:51.907376,session_start,56b4c156-3b3b-449f-8db0-18dfb3936d53,1,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,None,NaN,None,2024,11,None,None
2,20241113,2024-11-14 05:54:51.907376,page_view,56b4c156-3b3b-449f-8db0-18dfb3936d53,1,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,None,NaN,None,2024,11,None,None
3,20241113,2024-11-14 05:54:57.126554,user_session_info,56b4c156-3b3b-449f-8db0-18dfb3936d53,1,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,None,NaN,None,2024,11,_1731563690,_251617.1731563690
4,20241113,2024-11-14 05:55:08.384203,scroll,56b4c156-3b3b-449f-8db0-18dfb3936d53,1,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,None,NaN,None,2024,11,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260859,20241113,2024-11-14 03:17:08.166826,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,1,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,...,None,None,None,None,NaN,None,2024,11,_1731554221,_2145680768.1731554221
260860,20241113,2024-11-14 03:17:26.457025,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,1,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,...,None,None,None,None,NaN,None,2024,11,None,None
260861,20241113,2024-11-14 03:17:26.457025,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,1,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,...,None,None,None,None,NaN,None,2024,11,None,None
260862,20241113,2024-11-14 03:17:45.807694,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,1,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,...,None,None,None,None,NaN,None,2024,11,None,None
260863,20241113,2024-11-14 03:19:56.763039,user_engagement,df966189-a01b-4b3c-abe7-7d6b5481a98c,1,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,...,None,None,None,None,NaN,None,2024,11,None,None

In [11]:
df = reorder_columns(
    df,
    insert_after=["session_id", "ep_ga_session_number"],
    target_col="user_prop_user_client_id"
)

In [8]:
df

,event_date,event_timestamp,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,ep_batch_ordering_id,ep_page_title,...,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id,session_id,ep_ga_session_number
0,20241113,2024-11-14 05:54:51.907376,first_visit,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,NaN,None,2024,11,None,None,56b4c156-3b3b-449f-8db0-18dfb3936d53,1
1,20241113,2024-11-14 05:54:51.907376,session_start,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,NaN,None,2024,11,None,None,56b4c156-3b3b-449f-8db0-18dfb3936d53,1
2,20241113,2024-11-14 05:54:51.907376,page_view,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,NaN,None,2024,11,None,None,56b4c156-3b3b-449f-8db0-18dfb3936d53,1
3,20241113,2024-11-14 05:54:57.126554,user_session_info,1731563683537,None,https://www.shopko.com/,1.0,None,2,Shopko Optical Eye Care and Vision Centers,...,None,None,NaN,None,2024,11,_1731563690,_251617.1731563690,56b4c156-3b3b-449f-8db0-18dfb3936d53,1
4,20241113,2024-11-14 05:55:08.384203,scroll,1731563683537,None,https://www.shopko.com/,1.0,None,3,Shopko Optical Eye Care and Vision Centers,...,None,None,NaN,None,2024,11,None,None,56b4c156-3b3b-449f-8db0-18dfb3936d53,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260859,20241113,2024-11-14 03:17:08.166826,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,2,Eye Care Center in Bellevue - Shopko Optical,...,None,None,NaN,None,2024,11,_1731554221,_2145680768.1731554221,df966189-a01b-4b3c-abe7-7d6b5481a98c,1
260860,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,None,None,NaN,None,2024,11,None,None,df966189-a01b-4b3c-abe7-7d6b5481a98c,1
260861,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,None,None,NaN,None,2024,11,None,None,df966189-a01b-4b3c-abe7-7d6b5481a98c,1
260862,20241113,2024-11-14 03:17:45.807694,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,4,Eye Care Center in Bellevue - Shopko Optical,...,None,None,NaN,None,2024,11,None,None,df966189-a01b-4b3c-abe7-7d6b5481a98c,1
260863,20241113,2024-11-14 03:19:56.763039,user_engagement,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,5,Eye Care Center in Bellevue - Shopko Optical,...,None,None,NaN,None,2024,11,None,None,df966189-a01b-4b3c-abe7-7d6b5481a98c,1

In [5]:
df

,event_date,event_timestamp,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,ep_batch_ordering_id,ep_page_title,...,session_traffic_source_last_click_google_ads_campaign_campaign_name,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id,session_id
0,20241113,2024-11-14 05:54:51.907376,first_visit,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,None,NaN,None,2024,11,None,None,56b4c156-3b3b-449f-8db0-18dfb3936d53
1,20241113,2024-11-14 05:54:51.907376,session_start,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,None,NaN,None,2024,11,None,None,56b4c156-3b3b-449f-8db0-18dfb3936d53
2,20241113,2024-11-14 05:54:51.907376,page_view,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,None,NaN,None,2024,11,None,None,56b4c156-3b3b-449f-8db0-18dfb3936d53
3,20241113,2024-11-14 05:54:57.126554,user_session_info,1731563683537,None,https://www.shopko.com/,1.0,None,2,Shopko Optical Eye Care and Vision Centers,...,None,None,None,NaN,None,2024,11,_1731563690,_251617.1731563690,56b4c156-3b3b-449f-8db0-18dfb3936d53
4,20241113,2024-11-14 05:55:08.384203,scroll,1731563683537,None,https://www.shopko.com/,1.0,None,3,Shopko Optical Eye Care and Vision Centers,...,None,None,None,NaN,None,2024,11,None,None,56b4c156-3b3b-449f-8db0-18dfb3936d53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260859,20241113,2024-11-14 03:17:08.166826,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,2,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,NaN,None,2024,11,_1731554221,_2145680768.1731554221,df966189-a01b-4b3c-abe7-7d6b5481a98c
260860,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,NaN,None,2024,11,None,None,df966189-a01b-4b3c-abe7-7d6b5481a98c
260861,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,NaN,None,2024,11,None,None,df966189-a01b-4b3c-abe7-7d6b5481a98c
260862,20241113,2024-11-14 03:17:45.807694,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,4,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,NaN,None,2024,11,None,None,df966189-a01b-4b3c-abe7-7d6b5481a98c
260863,20241113,2024-11-14 03:19:56.763039,user_engagement,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,5,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,NaN,None,2024,11,None,None,df966189-a01b-4b3c-abe7-7d6b5481a98c

97675

In [3]:
longest_session = df['session_id'].value_counts().idxmax()
print(longest_session)

a7a92851-9159-4015-99a8-2aa7c33973f6

In [4]:
from urllib.parse import urlparse
# df['clean_page'] = df['param_page_location'].apply(
#     lambda url: urlparse(url).scheme + "://" + urlparse(url).netloc + urlparse(url).path 
#     if isinstance(url, str) else url
# )

df['clean_page'] = [
    f"{urlparse(url).scheme}://{urlparse(url).netloc}{urlparse(url).path}" 
    if isinstance(url, str) else url
    for url in df['ep_page_location']
]

df['pageview_id'] = [
    str(uuid.uuid5(uuid.NAMESPACE_DNS, f"{sid}_{page}"))
    for sid, page in zip(df['session_id'], df['clean_page'])
]

In [6]:
df[['clean_page', 'ep_page_location']]

,clean_page,ep_page_location
0,https://www.shopko.com/,https://www.shopko.com/
1,https://www.shopko.com/,https://www.shopko.com/
2,https://www.shopko.com/,https://www.shopko.com/
3,https://www.shopko.com/,https://www.shopko.com/
4,https://www.shopko.com/,https://www.shopko.com/
...,...,...
260859,https://www.shopko.com/eye-care/ne/bellevue/st...,https://www.shopko.com/eye-care/ne/bellevue/st...
260860,https://www.shopko.com/eye-care/ne/bellevue/st...,https://www.shopko.com/eye-care/ne/bellevue/st...
260861,https://www.shopko.com/eye-care/ne/bellevue/st...,https://www.shopko.com/eye-care/ne/bellevue/st...
260862,https://www.shopko.com/eye-care/ne/bellevue/st...,https://www.shopko.com/eye-care/ne/bellevue/st...
260863,https://www.shopko.com/eye-care/ne/bellevue/st...,https://www.shopko.com/eye-care/ne/bellevue/st...

In [10]:
# make sure pageview_id is already created
cols = list(df.columns)

# force desired order
desired_order = ['event_date', 'event_timestamp', 'session_id', 'pageview_id']

# put remaining columns after
new_order = desired_order + [c for c in cols if c not in desired_order]

# reorder DataFrame
df = df[new_order]

In [11]:
df

,event_date,event_timestamp,session_id,pageview_id,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,...,session_traffic_source_last_click_google_ads_campaign_campaign_name,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id,clean_page
0,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,first_visit,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,https://www.shopko.com/
1,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,session_start,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,https://www.shopko.com/
2,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,page_view,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,https://www.shopko.com/
3,20241113,2024-11-14 05:54:57.126554,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,user_session_info,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,NaN,None,2024,11,_1731563690,_251617.1731563690,https://www.shopko.com/
4,20241113,2024-11-14 05:55:08.384203,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,scroll,1731563683537,None,https://www.shopko.com/,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,https://www.shopko.com/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260859,20241113,2024-11-14 03:17:08.166826,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,...,None,None,None,NaN,None,2024,11,_1731554221,_2145680768.1731554221,https://www.shopko.com/eye-care/ne/bellevue/st...
260860,20241113,2024-11-14 03:17:26.457025,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,https://www.shopko.com/eye-care/ne/bellevue/st...
260861,20241113,2024-11-14 03:17:26.457025,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,https://www.shopko.com/eye-care/ne/bellevue/st...
260862,20241113,2024-11-14 03:17:45.807694,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,https://www.shopko.com/eye-care/ne/bellevue/st...
260863,20241113,2024-11-14 03:19:56.763039,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,user_engagement,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,...,None,None,None,NaN,None,2024,11,None,None,https://www.shopko.com/eye-care/ne/bellevue/st...

In [12]:
import uuid

def validate_pageview_ids(df):
    errors = []

    # Recalculate pageview_id using the same logic
    expected_ids = {
        (sid, page): str(uuid.uuid5(uuid.NAMESPACE_DNS, f"{sid}_{page}"))
        for sid, page in zip(df['session_id'], df['clean_page'])
    }

    # Compare with df['pageview_id_new']
    for i, row in df.iterrows():
        key = (row['session_id'], row['clean_page'])
        expected = expected_ids[key]
        actual = row['pageview_id']
        if expected != actual:
            errors.append((i, row['session_id'], row['clean_page'], actual, expected))

    if errors:
        print("❌ Inconsistencies found in pageview_id:")
        for err in errors:
            print(f"Row {err[0]} | session={err[1]} | page={err[2]}\n"
                  f"  actual:   {err[3]}\n"
                  f"  expected: {err[4]}\n")
    else:
        print("✅ All pageview_id_new values are correct!")

# Run validation
validate_pageview_ids(df)

✅ All pageview_id_new values are correct!

In [13]:
#drop clean column 
df.drop('clean_page', axis=1, inplace=True)

C:\Users\aalig\AppData\Local\Temp\ipykernel_21100\1991513025.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('clean_page', axis=1, inplace=True)

In [14]:
df.to_parquet('../parquet_output/events_pageview_identifier.parquet')