In [4]:
import pandas as pd
import uuid

In [5]:
df = pd.read_parquet('../parquet_output/events_normalized.parquet')
df.head(10)

,event_date,event_timestamp,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,ep_batch_ordering_id,ep_page_title,...,session_traffic_source_last_click_google_ads_campaign_campaign_id,session_traffic_source_last_click_google_ads_campaign_campaign_name,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id
0,20241113,1731513971041603,first_visit,1731513969906,prm,https://www.shopko.com/eye-care/il/crystal-lak...,1.0,productpickup,1,Eye Care Center in Crystal Lake - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,None,None
1,20241113,1731513971041603,session_start,1731513969906,prm,https://www.shopko.com/eye-care/il/crystal-lak...,1.0,productpickup,1,Eye Care Center in Crystal Lake - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,None,None
2,20241113,1731513971041603,page_view,1731513969906,prm,https://www.shopko.com/eye-care/il/crystal-lak...,1.0,productpickup,1,Eye Care Center in Crystal Lake - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,None,None
3,20241113,1731513976070304,user_session_info,1731513969906,None,https://www.shopko.com/eye-care/il/crystal-lak...,1.0,None,2,Eye Care Center in Crystal Lake - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,_1731513970,_2091574202.1731513971
4,20241113,1731513976070304,scroll,1731513969906,None,https://www.shopko.com/eye-care/il/crystal-lak...,1.0,None,2,Eye Care Center in Crystal Lake - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,_1731513970,_2091574202.1731513971
5,20241113,1731513976070304,scroll,1731513969906,None,https://www.shopko.com/eye-care/il/crystal-lak...,1.0,None,2,Eye Care Center in Crystal Lake - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,_1731513970,_2091574202.1731513971
6,20241113,1731513976070304,scroll,1731513969906,None,https://www.shopko.com/eye-care/il/crystal-lak...,1.0,None,2,Eye Care Center in Crystal Lake - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,_1731513970,_2091574202.1731513971
7,20241113,1731513976070304,scroll,1731513969906,None,https://www.shopko.com/eye-care/il/crystal-lak...,1.0,None,2,Eye Care Center in Crystal Lake - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,_1731513970,_2091574202.1731513971
8,20241113,1731513989510264,user_engagement,1731513969906,None,https://www.shopko.com/eye-care/il/crystal-lak...,1.0,None,3,Eye Care Center in Crystal Lake - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,None,None
9,20241113,1731517607583742,first_visit,1731517607162,prm,https://www.shopko.com/eye-care/ia/ankeny/stor...,1.0,productpickup,1,Eye Care Center in Ankeny - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,None,None

In [6]:
df['event_timestamp'] = pd.to_datetime(df['event_timestamp'], unit='us')
df

,event_date,event_timestamp,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,ep_batch_ordering_id,ep_page_title,...,session_traffic_source_last_click_google_ads_campaign_campaign_id,session_traffic_source_last_click_google_ads_campaign_campaign_name,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id
0,20241113,2024-11-13 16:06:11.041603,first_visit,1731513969906,prm,https://www.shopko.com/eye-care/il/crystal-lak...,1.0,productpickup,1,Eye Care Center in Crystal Lake - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,None,None
1,20241113,2024-11-13 16:06:11.041603,session_start,1731513969906,prm,https://www.shopko.com/eye-care/il/crystal-lak...,1.0,productpickup,1,Eye Care Center in Crystal Lake - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,None,None
2,20241113,2024-11-13 16:06:11.041603,page_view,1731513969906,prm,https://www.shopko.com/eye-care/il/crystal-lak...,1.0,productpickup,1,Eye Care Center in Crystal Lake - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,None,None
3,20241113,2024-11-13 16:06:16.070304,user_session_info,1731513969906,None,https://www.shopko.com/eye-care/il/crystal-lak...,1.0,None,2,Eye Care Center in Crystal Lake - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,_1731513970,_2091574202.1731513971
4,20241113,2024-11-13 16:06:16.070304,scroll,1731513969906,None,https://www.shopko.com/eye-care/il/crystal-lak...,1.0,None,2,Eye Care Center in Crystal Lake - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,_1731513970,_2091574202.1731513971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260859,20241113,2024-11-14 02:43:12.524186,user_session_info,1731552185721,None,https://www.shopko.com/eye-care/?utm_source=em...,1.0,None,2,Eye Exam Center Locations Near You,...,None,None,None,None,NaN,None,2024,11,_1731552186,_1436230623.1728949201
260860,20241113,2024-11-14 02:43:12.524186,scroll,1731552185721,None,https://www.shopko.com/eye-care/?utm_source=em...,1.0,None,2,Eye Exam Center Locations Near You,...,None,None,None,None,NaN,None,2024,11,_1731552186,_1436230623.1728949201
260861,20241113,2024-11-14 02:43:12.524186,scroll,1731552185721,None,https://www.shopko.com/eye-care/?utm_source=em...,1.0,None,2,Eye Exam Center Locations Near You,...,None,None,None,None,NaN,None,2024,11,_1731552186,_1436230623.1728949201
260862,20241113,2024-11-14 02:43:12.524186,scroll,1731552185721,None,https://www.shopko.com/eye-care/?utm_source=em...,1.0,None,2,Eye Exam Center Locations Near You,...,None,None,None,None,NaN,None,2024,11,_1731552186,_1436230623.1728949201
260863,20241113,2024-11-14 02:44:47.997389,user_engagement,1731552185721,None,https://www.shopko.com/eye-care/?utm_source=em...,1.0,None,3,Eye Exam Center Locations Near You,...,None,None,None,None,NaN,None,2024,11,None,None

In [7]:
df = df.sort_values(['user_pseudo_id', 'event_timestamp'])
df

,event_date,event_timestamp,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,ep_batch_ordering_id,ep_page_title,...,session_traffic_source_last_click_google_ads_campaign_campaign_id,session_traffic_source_last_click_google_ads_campaign_campaign_name,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id
77383,20241113,2024-11-14 05:54:51.907376,first_visit,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,None,None,NaN,None,2024,11,None,None
77384,20241113,2024-11-14 05:54:51.907376,session_start,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,None,None,NaN,None,2024,11,None,None
77385,20241113,2024-11-14 05:54:51.907376,page_view,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,None,None,NaN,None,2024,11,None,None
77386,20241113,2024-11-14 05:54:57.126554,user_session_info,1731563683537,None,https://www.shopko.com/,1.0,None,2,Shopko Optical Eye Care and Vision Centers,...,None,None,None,None,NaN,None,2024,11,_1731563690,_251617.1731563690
77387,20241113,2024-11-14 05:55:08.384203,scroll,1731563683537,None,https://www.shopko.com/,1.0,None,3,Shopko Optical Eye Care and Vision Centers,...,None,None,None,None,NaN,None,2024,11,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124188,20241113,2024-11-14 03:17:08.166826,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,2,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,_1731554221,_2145680768.1731554221
124189,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,None,None
124190,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,None,None
124191,20241113,2024-11-14 03:17:45.807694,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,4,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,None,None
124192,20241113,2024-11-14 03:19:56.763039,user_engagement,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,5,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,None,NaN,None,2024,11,None,None

In [8]:
session_timeout = pd.Timedelta(minutes=30)
session_timeout

Timedelta('0 days 00:30:00')

In [9]:
df['prev_timestamp'] = df.groupby('user_pseudo_id')['event_timestamp'].shift()
df

,event_date,event_timestamp,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,ep_batch_ordering_id,ep_page_title,...,session_traffic_source_last_click_google_ads_campaign_campaign_name,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id,prev_timestamp
77383,20241113,2024-11-14 05:54:51.907376,first_visit,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,None,NaN,None,2024,11,None,None,NaT
77384,20241113,2024-11-14 05:54:51.907376,session_start,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,None,NaN,None,2024,11,None,None,2024-11-14 05:54:51.907376
77385,20241113,2024-11-14 05:54:51.907376,page_view,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,None,NaN,None,2024,11,None,None,2024-11-14 05:54:51.907376
77386,20241113,2024-11-14 05:54:57.126554,user_session_info,1731563683537,None,https://www.shopko.com/,1.0,None,2,Shopko Optical Eye Care and Vision Centers,...,None,None,None,NaN,None,2024,11,_1731563690,_251617.1731563690,2024-11-14 05:54:51.907376
77387,20241113,2024-11-14 05:55:08.384203,scroll,1731563683537,None,https://www.shopko.com/,1.0,None,3,Shopko Optical Eye Care and Vision Centers,...,None,None,None,NaN,None,2024,11,None,None,2024-11-14 05:54:57.126554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124188,20241113,2024-11-14 03:17:08.166826,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,2,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,NaN,None,2024,11,_1731554221,_2145680768.1731554221,2024-11-14 03:17:08.166826
124189,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,NaN,None,2024,11,None,None,2024-11-14 03:17:08.166826
124190,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,NaN,None,2024,11,None,None,2024-11-14 03:17:26.457025
124191,20241113,2024-11-14 03:17:45.807694,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,4,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,NaN,None,2024,11,None,None,2024-11-14 03:17:26.457025
124192,20241113,2024-11-14 03:19:56.763039,user_engagement,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,5,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,NaN,None,2024,11,None,None,2024-11-14 03:17:45.807694

In [10]:
df['time_diff'] = pd.to_datetime(df['event_timestamp']) - pd.to_datetime(df['prev_timestamp'])
df

,event_date,event_timestamp,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,ep_batch_ordering_id,ep_page_title,...,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id,prev_timestamp,time_diff
77383,20241113,2024-11-14 05:54:51.907376,first_visit,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,NaN,None,2024,11,None,None,NaT,NaT
77384,20241113,2024-11-14 05:54:51.907376,session_start,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,NaN,None,2024,11,None,None,2024-11-14 05:54:51.907376,0 days 00:00:00
77385,20241113,2024-11-14 05:54:51.907376,page_view,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,NaN,None,2024,11,None,None,2024-11-14 05:54:51.907376,0 days 00:00:00
77386,20241113,2024-11-14 05:54:57.126554,user_session_info,1731563683537,None,https://www.shopko.com/,1.0,None,2,Shopko Optical Eye Care and Vision Centers,...,None,None,NaN,None,2024,11,_1731563690,_251617.1731563690,2024-11-14 05:54:51.907376,0 days 00:00:05.219178
77387,20241113,2024-11-14 05:55:08.384203,scroll,1731563683537,None,https://www.shopko.com/,1.0,None,3,Shopko Optical Eye Care and Vision Centers,...,None,None,NaN,None,2024,11,None,None,2024-11-14 05:54:57.126554,0 days 00:00:11.257649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124188,20241113,2024-11-14 03:17:08.166826,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,2,Eye Care Center in Bellevue - Shopko Optical,...,None,None,NaN,None,2024,11,_1731554221,_2145680768.1731554221,2024-11-14 03:17:08.166826,0 days 00:00:00
124189,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,None,None,NaN,None,2024,11,None,None,2024-11-14 03:17:08.166826,0 days 00:00:18.290199
124190,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,None,None,NaN,None,2024,11,None,None,2024-11-14 03:17:26.457025,0 days 00:00:00
124191,20241113,2024-11-14 03:17:45.807694,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,4,Eye Care Center in Bellevue - Shopko Optical,...,None,None,NaN,None,2024,11,None,None,2024-11-14 03:17:26.457025,0 days 00:00:19.350669
124192,20241113,2024-11-14 03:19:56.763039,user_engagement,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,5,Eye Care Center in Bellevue - Shopko Optical,...,None,None,NaN,None,2024,11,None,None,2024-11-14 03:17:45.807694,0 days 00:02:10.955345

In [11]:
df['new_session'] = (df['time_diff'] > session_timeout) | (df['time_diff'].isna())
df

,event_date,event_timestamp,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,ep_batch_ordering_id,ep_page_title,...,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id,prev_timestamp,time_diff,new_session
77383,20241113,2024-11-14 05:54:51.907376,first_visit,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,NaN,None,2024,11,None,None,NaT,NaT,True
77384,20241113,2024-11-14 05:54:51.907376,session_start,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,NaN,None,2024,11,None,None,2024-11-14 05:54:51.907376,0 days 00:00:00,False
77385,20241113,2024-11-14 05:54:51.907376,page_view,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,NaN,None,2024,11,None,None,2024-11-14 05:54:51.907376,0 days 00:00:00,False
77386,20241113,2024-11-14 05:54:57.126554,user_session_info,1731563683537,None,https://www.shopko.com/,1.0,None,2,Shopko Optical Eye Care and Vision Centers,...,None,NaN,None,2024,11,_1731563690,_251617.1731563690,2024-11-14 05:54:51.907376,0 days 00:00:05.219178,False
77387,20241113,2024-11-14 05:55:08.384203,scroll,1731563683537,None,https://www.shopko.com/,1.0,None,3,Shopko Optical Eye Care and Vision Centers,...,None,NaN,None,2024,11,None,None,2024-11-14 05:54:57.126554,0 days 00:00:11.257649,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124188,20241113,2024-11-14 03:17:08.166826,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,2,Eye Care Center in Bellevue - Shopko Optical,...,None,NaN,None,2024,11,_1731554221,_2145680768.1731554221,2024-11-14 03:17:08.166826,0 days 00:00:00,False
124189,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,None,NaN,None,2024,11,None,None,2024-11-14 03:17:08.166826,0 days 00:00:18.290199,False
124190,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,None,NaN,None,2024,11,None,None,2024-11-14 03:17:26.457025,0 days 00:00:00,False
124191,20241113,2024-11-14 03:17:45.807694,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,4,Eye Care Center in Bellevue - Shopko Optical,...,None,NaN,None,2024,11,None,None,2024-11-14 03:17:26.457025,0 days 00:00:19.350669,False
124192,20241113,2024-11-14 03:19:56.763039,user_engagement,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,5,Eye Care Center in Bellevue - Shopko Optical,...,None,NaN,None,2024,11,None,None,2024-11-14 03:17:45.807694,0 days 00:02:10.955345,False

In [12]:
df['session_id'] = df.groupby('user_pseudo_id')['new_session'].cumsum()
df

,event_date,event_timestamp,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,ep_batch_ordering_id,ep_page_title,...,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id,prev_timestamp,time_diff,new_session,session_id
77383,20241113,2024-11-14 05:54:51.907376,first_visit,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,NaN,None,2024,11,None,None,NaT,NaT,True,1
77384,20241113,2024-11-14 05:54:51.907376,session_start,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,NaN,None,2024,11,None,None,2024-11-14 05:54:51.907376,0 days 00:00:00,False,1
77385,20241113,2024-11-14 05:54:51.907376,page_view,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,NaN,None,2024,11,None,None,2024-11-14 05:54:51.907376,0 days 00:00:00,False,1
77386,20241113,2024-11-14 05:54:57.126554,user_session_info,1731563683537,None,https://www.shopko.com/,1.0,None,2,Shopko Optical Eye Care and Vision Centers,...,NaN,None,2024,11,_1731563690,_251617.1731563690,2024-11-14 05:54:51.907376,0 days 00:00:05.219178,False,1
77387,20241113,2024-11-14 05:55:08.384203,scroll,1731563683537,None,https://www.shopko.com/,1.0,None,3,Shopko Optical Eye Care and Vision Centers,...,NaN,None,2024,11,None,None,2024-11-14 05:54:57.126554,0 days 00:00:11.257649,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124188,20241113,2024-11-14 03:17:08.166826,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,2,Eye Care Center in Bellevue - Shopko Optical,...,NaN,None,2024,11,_1731554221,_2145680768.1731554221,2024-11-14 03:17:08.166826,0 days 00:00:00,False,1
124189,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,NaN,None,2024,11,None,None,2024-11-14 03:17:08.166826,0 days 00:00:18.290199,False,1
124190,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,NaN,None,2024,11,None,None,2024-11-14 03:17:26.457025,0 days 00:00:00,False,1
124191,20241113,2024-11-14 03:17:45.807694,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,4,Eye Care Center in Bellevue - Shopko Optical,...,NaN,None,2024,11,None,None,2024-11-14 03:17:26.457025,0 days 00:00:19.350669,False,1
124192,20241113,2024-11-14 03:19:56.763039,user_engagement,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,5,Eye Care Center in Bellevue - Shopko Optical,...,NaN,None,2024,11,None,None,2024-11-14 03:17:45.807694,0 days 00:02:10.955345,False,1

In [13]:
df['session_id'] = df['new_session'].apply(lambda x: str(uuid.uuid4()) if x else None)
df['session_id'] = df.groupby('user_pseudo_id')['session_id'].ffill()

In [14]:
df.drop(columns=['prev_timestamp', 'time_diff', 'new_session'], inplace=True)

In [15]:
df

,event_date,event_timestamp,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,ep_batch_ordering_id,ep_page_title,...,session_traffic_source_last_click_google_ads_campaign_campaign_name,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id,session_id
77383,20241113,2024-11-14 05:54:51.907376,first_visit,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,None,NaN,None,2024,11,None,None,56b4c156-3b3b-449f-8db0-18dfb3936d53
77384,20241113,2024-11-14 05:54:51.907376,session_start,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,None,NaN,None,2024,11,None,None,56b4c156-3b3b-449f-8db0-18dfb3936d53
77385,20241113,2024-11-14 05:54:51.907376,page_view,1731563683537,None,https://www.shopko.com/,1.0,None,1,Shopko Optical Eye Care and Vision Centers,...,None,None,None,NaN,None,2024,11,None,None,56b4c156-3b3b-449f-8db0-18dfb3936d53
77386,20241113,2024-11-14 05:54:57.126554,user_session_info,1731563683537,None,https://www.shopko.com/,1.0,None,2,Shopko Optical Eye Care and Vision Centers,...,None,None,None,NaN,None,2024,11,_1731563690,_251617.1731563690,56b4c156-3b3b-449f-8db0-18dfb3936d53
77387,20241113,2024-11-14 05:55:08.384203,scroll,1731563683537,None,https://www.shopko.com/,1.0,None,3,Shopko Optical Eye Care and Vision Centers,...,None,None,None,NaN,None,2024,11,None,None,56b4c156-3b3b-449f-8db0-18dfb3936d53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124188,20241113,2024-11-14 03:17:08.166826,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,2,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,NaN,None,2024,11,_1731554221,_2145680768.1731554221,df966189-a01b-4b3c-abe7-7d6b5481a98c
124189,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,NaN,None,2024,11,None,None,df966189-a01b-4b3c-abe7-7d6b5481a98c
124190,20241113,2024-11-14 03:17:26.457025,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,NaN,None,2024,11,None,None,df966189-a01b-4b3c-abe7-7d6b5481a98c
124191,20241113,2024-11-14 03:17:45.807694,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,4,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,NaN,None,2024,11,None,None,df966189-a01b-4b3c-abe7-7d6b5481a98c
124192,20241113,2024-11-14 03:19:56.763039,user_engagement,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,5,Eye Care Center in Bellevue - Shopko Optical,...,None,None,None,NaN,None,2024,11,None,None,df966189-a01b-4b3c-abe7-7d6b5481a98c

In [16]:
df['session_id'].value_counts()

session_id
a7a92851-9159-4015-99a8-2aa7c33973f6    924
82216b6f-ddbe-4bbf-a69e-d82e23157e5c    870
f56187a0-dbd5-41f2-8615-5c569c47f2c9    860
388be873-2347-42dd-91b9-9ce05ee6f46f    767
3cf40e15-7ee1-4d99-bd4c-6c4dc4e77af5    746
                                       ...
d1eb1734-a486-47f8-9aad-10644dfc9992      2
ba8fac44-7b95-4342-bb12-7a62e57a725b      2
344196e7-018a-4e17-bcb9-a323b4ef28ea      2
0761c29d-c237-4134-88aa-05fb6779904a      1
c620de5e-5204-4a71-96d8-500a30b7a876      1
Name: count, Length: 5560, dtype: int64

In [17]:
cols = list(df.columns)

# remove session_id and reinsert it after event_timestamp
cols.insert(cols.index('event_timestamp') + 1, cols.pop(cols.index('session_id')))

df = df[cols]

In [18]:
df

,event_date,event_timestamp,session_id,event_name,ep_batch_page_id,ep_source,ep_page_location,ep_engaged_session_event,ep_campaign,ep_batch_ordering_id,...,session_traffic_source_last_click_google_ads_campaign_campaign_id,session_traffic_source_last_click_google_ads_campaign_campaign_name,session_traffic_source_last_click_google_ads_campaign_ad_group_id,session_traffic_source_last_click_google_ads_campaign_ad_group_name,user_ltv_revenue,user_ltv_currency,year,month,user_prop_user_session_id,user_prop_user_client_id
77383,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,first_visit,1731563683537,None,https://www.shopko.com/,1.0,None,1,...,None,None,None,None,NaN,None,2024,11,None,None
77384,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,session_start,1731563683537,None,https://www.shopko.com/,1.0,None,1,...,None,None,None,None,NaN,None,2024,11,None,None
77385,20241113,2024-11-14 05:54:51.907376,56b4c156-3b3b-449f-8db0-18dfb3936d53,page_view,1731563683537,None,https://www.shopko.com/,1.0,None,1,...,None,None,None,None,NaN,None,2024,11,None,None
77386,20241113,2024-11-14 05:54:57.126554,56b4c156-3b3b-449f-8db0-18dfb3936d53,user_session_info,1731563683537,None,https://www.shopko.com/,1.0,None,2,...,None,None,None,None,NaN,None,2024,11,_1731563690,_251617.1731563690
77387,20241113,2024-11-14 05:55:08.384203,56b4c156-3b3b-449f-8db0-18dfb3936d53,scroll,1731563683537,None,https://www.shopko.com/,1.0,None,3,...,None,None,None,None,NaN,None,2024,11,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124188,20241113,2024-11-14 03:17:08.166826,df966189-a01b-4b3c-abe7-7d6b5481a98c,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,2,...,None,None,None,None,NaN,None,2024,11,_1731554221,_2145680768.1731554221
124189,20241113,2024-11-14 03:17:26.457025,df966189-a01b-4b3c-abe7-7d6b5481a98c,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,...,None,None,None,None,NaN,None,2024,11,None,None
124190,20241113,2024-11-14 03:17:26.457025,df966189-a01b-4b3c-abe7-7d6b5481a98c,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,3,...,None,None,None,None,NaN,None,2024,11,None,None
124191,20241113,2024-11-14 03:17:45.807694,df966189-a01b-4b3c-abe7-7d6b5481a98c,scroll,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,4,...,None,None,None,None,NaN,None,2024,11,None,None
124192,20241113,2024-11-14 03:19:56.763039,df966189-a01b-4b3c-abe7-7d6b5481a98c,user_engagement,1731554220483,None,https://www.shopko.com/eye-care/ne/bellevue/st...,1.0,None,5,...,None,None,None,None,NaN,None,2024,11,None,None

In [19]:
df.to_parquet('../parquet_output/events_session_identifier.parquet', index=False)

In [20]:
df['session_id'].nunique()

5560