In [21]:
import pandas as pd

In [22]:
events_data = pd.read_parquet('../parquet_output/events_normalized.parquet')
events_data

,event_date,event_timestamp,event_name,event_previous_timestamp,event_value_in_usd,event_bundle_sequence_id,event_server_timestamp_offset,user_id,user_pseudo_id,user_first_touch_timestamp,...,param_click_classes,param_click_id,param_value,param_link_text,param_file_extension,param_file_name,param_link_url,param_content,user_prop_user_session_id,user_prop_user_client_id
0,20241113,1731513971041603,first_visit,NaN,NaN,-2094340797,NaN,NaN,2.091574e+09,1.731514e+15,...,None,None,NaN,None,None,None,None,None,None,None
1,20241113,1731513971041603,session_start,NaN,NaN,-2094340797,NaN,NaN,2.091574e+09,1.731514e+15,...,None,None,NaN,None,None,None,None,None,None,None
2,20241113,1731513971041603,page_view,NaN,NaN,-2094340797,NaN,NaN,2.091574e+09,1.731514e+15,...,None,None,NaN,None,None,None,None,None,None,None
3,20241113,1731513976070304,user_session_info,NaN,NaN,-2089312096,NaN,NaN,2.091574e+09,1.731514e+15,...,None,None,NaN,None,None,None,None,None,_1731513970,_2091574202.1731513971
4,20241113,1731513976070304,scroll,NaN,NaN,-2089312096,NaN,NaN,2.091574e+09,1.731514e+15,...,None,None,NaN,None,None,None,None,None,_1731513970,_2091574202.1731513971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260859,20241113,1731552192524186,user_session_info,NaN,NaN,1767403418,NaN,NaN,1.436231e+09,1.728949e+15,...,None,None,NaN,None,None,None,None,None,_1731552186,_1436230623.1728949201
260860,20241113,1731552192524186,scroll,NaN,NaN,1767403418,NaN,NaN,1.436231e+09,1.728949e+15,...,None,None,NaN,None,None,None,None,None,_1731552186,_1436230623.1728949201
260861,20241113,1731552192524186,scroll,NaN,NaN,1767403418,NaN,NaN,1.436231e+09,1.728949e+15,...,None,None,NaN,None,None,None,None,None,_1731552186,_1436230623.1728949201
260862,20241113,1731552192524186,scroll,NaN,NaN,1767403418,NaN,NaN,1.436231e+09,1.728949e+15,...,None,None,NaN,None,None,None,None,None,_1731552186,_1436230623.1728949201
260863,20241113,1731552287997389,user_engagement,NaN,NaN,1862876621,NaN,NaN,1.436231e+09,1.728949e+15,...,None,None,NaN,None,None,None,None,None,None,None

In [23]:
events_session = events_data[['event_timestamp', 'user_pseudo_id']]
events_session

         event_timestamp  user_pseudo_id
0       1731513971041603    2.091574e+09
1       1731513971041603    2.091574e+09
2       1731513971041603    2.091574e+09
3       1731513976070304    2.091574e+09
4       1731513976070304    2.091574e+09
...                  ...             ...
260859  1731552192524186    1.436231e+09
260860  1731552192524186    1.436231e+09
260861  1731552192524186    1.436231e+09
260862  1731552192524186    1.436231e+09
260863  1731552287997389    1.436231e+09

[260864 rows x 2 columns]

In [24]:
df = events_session

In [25]:
df['event_timestamp'] = pd.to_datetime(df['event_timestamp'], unit='us')
# df['event_timestamp'] = df['event_timestamp'].dt.strftime('%Y-%m-%d %H:%M:%S')

C:\Users\aalig\AppData\Local\Temp\ipykernel_16776\1166858282.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['event_timestamp'] = pd.to_datetime(df['event_timestamp'], unit='us')

In [26]:
time = pd.to_datetime(1731513971041603, unit='us')
time

Timestamp('2024-11-13 16:06:11.041603')

In [27]:
df

                  event_timestamp  user_pseudo_id
0      2024-11-13 16:06:11.041603    2.091574e+09
1      2024-11-13 16:06:11.041603    2.091574e+09
2      2024-11-13 16:06:11.041603    2.091574e+09
3      2024-11-13 16:06:16.070304    2.091574e+09
4      2024-11-13 16:06:16.070304    2.091574e+09
...                           ...             ...
260859 2024-11-14 02:43:12.524186    1.436231e+09
260860 2024-11-14 02:43:12.524186    1.436231e+09
260861 2024-11-14 02:43:12.524186    1.436231e+09
260862 2024-11-14 02:43:12.524186    1.436231e+09
260863 2024-11-14 02:44:47.997389    1.436231e+09

[260864 rows x 2 columns]

In [28]:
df['user_pseudo_id'].value_counts()

user_pseudo_id
9.230632e+08    1092
9.009409e+08     924
1.237394e+08     883
8.416615e+08     860
8.722080e+08     810
                ...
1.155554e+09       2
1.510363e+09       2
1.846422e+08       2
1.566922e+09       2
1.279898e+09       2
Name: count, Length: 4740, dtype: int64

In [29]:
df = df.sort_values(['user_pseudo_id', 'event_timestamp'])
df

                  event_timestamp  user_pseudo_id
77383  2024-11-14 05:54:51.907376    2.516172e+05
77384  2024-11-14 05:54:51.907376    2.516172e+05
77385  2024-11-14 05:54:51.907376    2.516172e+05
77386  2024-11-14 05:54:57.126554    2.516172e+05
77387  2024-11-14 05:55:08.384203    2.516172e+05
...                           ...             ...
124188 2024-11-14 03:17:08.166826    2.145681e+09
124189 2024-11-14 03:17:26.457025    2.145681e+09
124190 2024-11-14 03:17:26.457025    2.145681e+09
124191 2024-11-14 03:17:45.807694    2.145681e+09
124192 2024-11-14 03:19:56.763039    2.145681e+09

[260864 rows x 2 columns]

In [30]:
session_timeout = pd.Timedelta(minutes=30)
session_timeout

Timedelta('0 days 00:30:00')

In [31]:
df['prev_timestamp'] = df.groupby('user_pseudo_id')['event_timestamp'].shift()
df

                  event_timestamp  user_pseudo_id             prev_timestamp
77383  2024-11-14 05:54:51.907376    2.516172e+05                        NaT
77384  2024-11-14 05:54:51.907376    2.516172e+05 2024-11-14 05:54:51.907376
77385  2024-11-14 05:54:51.907376    2.516172e+05 2024-11-14 05:54:51.907376
77386  2024-11-14 05:54:57.126554    2.516172e+05 2024-11-14 05:54:51.907376
77387  2024-11-14 05:55:08.384203    2.516172e+05 2024-11-14 05:54:57.126554
...                           ...             ...                        ...
124188 2024-11-14 03:17:08.166826    2.145681e+09 2024-11-14 03:17:08.166826
124189 2024-11-14 03:17:26.457025    2.145681e+09 2024-11-14 03:17:08.166826
124190 2024-11-14 03:17:26.457025    2.145681e+09 2024-11-14 03:17:26.457025
124191 2024-11-14 03:17:45.807694    2.145681e+09 2024-11-14 03:17:26.457025
124192 2024-11-14 03:19:56.763039    2.145681e+09 2024-11-14 03:17:45.807694

[260864 rows x 3 columns]

In [32]:
df['time_diff'] = pd.to_datetime(df['event_timestamp']) - pd.to_datetime(df['prev_timestamp'])
df

,event_timestamp,user_pseudo_id,prev_timestamp,time_diff
77383,2024-11-14 05:54:51.907376,2.516172e+05,NaT,NaT
77384,2024-11-14 05:54:51.907376,2.516172e+05,2024-11-14 05:54:51.907376,0 days 00:00:00
77385,2024-11-14 05:54:51.907376,2.516172e+05,2024-11-14 05:54:51.907376,0 days 00:00:00
77386,2024-11-14 05:54:57.126554,2.516172e+05,2024-11-14 05:54:51.907376,0 days 00:00:05.219178
77387,2024-11-14 05:55:08.384203,2.516172e+05,2024-11-14 05:54:57.126554,0 days 00:00:11.257649
...,...,...,...,...
124188,2024-11-14 03:17:08.166826,2.145681e+09,2024-11-14 03:17:08.166826,0 days 00:00:00
124189,2024-11-14 03:17:26.457025,2.145681e+09,2024-11-14 03:17:08.166826,0 days 00:00:18.290199
124190,2024-11-14 03:17:26.457025,2.145681e+09,2024-11-14 03:17:26.457025,0 days 00:00:00
124191,2024-11-14 03:17:45.807694,2.145681e+09,2024-11-14 03:17:26.457025,0 days 00:00:19.350669
124192,2024-11-14 03:19:56.763039,2.145681e+09,2024-11-14 03:17:45.807694,0 days 00:02:10.955345

In [33]:
df['new_session'] = (df['time_diff'] > session_timeout) | (df['time_diff'].isna())
df

,event_timestamp,user_pseudo_id,prev_timestamp,time_diff,new_session
77383,2024-11-14 05:54:51.907376,2.516172e+05,NaT,NaT,True
77384,2024-11-14 05:54:51.907376,2.516172e+05,2024-11-14 05:54:51.907376,0 days 00:00:00,False
77385,2024-11-14 05:54:51.907376,2.516172e+05,2024-11-14 05:54:51.907376,0 days 00:00:00,False
77386,2024-11-14 05:54:57.126554,2.516172e+05,2024-11-14 05:54:51.907376,0 days 00:00:05.219178,False
77387,2024-11-14 05:55:08.384203,2.516172e+05,2024-11-14 05:54:57.126554,0 days 00:00:11.257649,False
...,...,...,...,...,...
124188,2024-11-14 03:17:08.166826,2.145681e+09,2024-11-14 03:17:08.166826,0 days 00:00:00,False
124189,2024-11-14 03:17:26.457025,2.145681e+09,2024-11-14 03:17:08.166826,0 days 00:00:18.290199,False
124190,2024-11-14 03:17:26.457025,2.145681e+09,2024-11-14 03:17:26.457025,0 days 00:00:00,False
124191,2024-11-14 03:17:45.807694,2.145681e+09,2024-11-14 03:17:26.457025,0 days 00:00:19.350669,False
124192,2024-11-14 03:19:56.763039,2.145681e+09,2024-11-14 03:17:45.807694,0 days 00:02:10.955345,False

In [34]:
df['session_id'] = df.groupby('user_pseudo_id')['new_session'].cumsum()
df

,event_timestamp,user_pseudo_id,prev_timestamp,time_diff,new_session,session_id
77383,2024-11-14 05:54:51.907376,2.516172e+05,NaT,NaT,True,1
77384,2024-11-14 05:54:51.907376,2.516172e+05,2024-11-14 05:54:51.907376,0 days 00:00:00,False,1
77385,2024-11-14 05:54:51.907376,2.516172e+05,2024-11-14 05:54:51.907376,0 days 00:00:00,False,1
77386,2024-11-14 05:54:57.126554,2.516172e+05,2024-11-14 05:54:51.907376,0 days 00:00:05.219178,False,1
77387,2024-11-14 05:55:08.384203,2.516172e+05,2024-11-14 05:54:57.126554,0 days 00:00:11.257649,False,1
...,...,...,...,...,...,...
124188,2024-11-14 03:17:08.166826,2.145681e+09,2024-11-14 03:17:08.166826,0 days 00:00:00,False,1
124189,2024-11-14 03:17:26.457025,2.145681e+09,2024-11-14 03:17:08.166826,0 days 00:00:18.290199,False,1
124190,2024-11-14 03:17:26.457025,2.145681e+09,2024-11-14 03:17:26.457025,0 days 00:00:00,False,1
124191,2024-11-14 03:17:45.807694,2.145681e+09,2024-11-14 03:17:26.457025,0 days 00:00:19.350669,False,1
124192,2024-11-14 03:19:56.763039,2.145681e+09,2024-11-14 03:17:45.807694,0 days 00:02:10.955345,False,1

In [35]:
df['session_id'] = df['user_pseudo_id'].astype(str) + '_' + df['session_id'].astype(str)
df

,event_timestamp,user_pseudo_id,prev_timestamp,time_diff,new_session,session_id
77383,2024-11-14 05:54:51.907376,2.516172e+05,NaT,NaT,True,251617.173156369_1
77384,2024-11-14 05:54:51.907376,2.516172e+05,2024-11-14 05:54:51.907376,0 days 00:00:00,False,251617.173156369_1
77385,2024-11-14 05:54:51.907376,2.516172e+05,2024-11-14 05:54:51.907376,0 days 00:00:00,False,251617.173156369_1
77386,2024-11-14 05:54:57.126554,2.516172e+05,2024-11-14 05:54:51.907376,0 days 00:00:05.219178,False,251617.173156369_1
77387,2024-11-14 05:55:08.384203,2.516172e+05,2024-11-14 05:54:57.126554,0 days 00:00:11.257649,False,251617.173156369_1
...,...,...,...,...,...,...
124188,2024-11-14 03:17:08.166826,2.145681e+09,2024-11-14 03:17:08.166826,0 days 00:00:00,False,2145680768.1731555_1
124189,2024-11-14 03:17:26.457025,2.145681e+09,2024-11-14 03:17:08.166826,0 days 00:00:18.290199,False,2145680768.1731555_1
124190,2024-11-14 03:17:26.457025,2.145681e+09,2024-11-14 03:17:26.457025,0 days 00:00:00,False,2145680768.1731555_1
124191,2024-11-14 03:17:45.807694,2.145681e+09,2024-11-14 03:17:26.457025,0 days 00:00:19.350669,False,2145680768.1731555_1
124192,2024-11-14 03:19:56.763039,2.145681e+09,2024-11-14 03:17:45.807694,0 days 00:02:10.955345,False,2145680768.1731555_1

In [36]:
df.drop(columns=['prev_timestamp', 'time_diff', 'new_session'], inplace=True)
df

                  event_timestamp  user_pseudo_id            session_id
77383  2024-11-14 05:54:51.907376    2.516172e+05    251617.173156369_1
77384  2024-11-14 05:54:51.907376    2.516172e+05    251617.173156369_1
77385  2024-11-14 05:54:51.907376    2.516172e+05    251617.173156369_1
77386  2024-11-14 05:54:57.126554    2.516172e+05    251617.173156369_1
77387  2024-11-14 05:55:08.384203    2.516172e+05    251617.173156369_1
...                           ...             ...                   ...
124188 2024-11-14 03:17:08.166826    2.145681e+09  2145680768.1731555_1
124189 2024-11-14 03:17:26.457025    2.145681e+09  2145680768.1731555_1
124190 2024-11-14 03:17:26.457025    2.145681e+09  2145680768.1731555_1
124191 2024-11-14 03:17:45.807694    2.145681e+09  2145680768.1731555_1
124192 2024-11-14 03:19:56.763039    2.145681e+09  2145680768.1731555_1

[260864 rows x 3 columns]

In [37]:
# total sessions
df['session_id'].nunique()

5560

In [38]:
def validate_sessions(df, session_timeout_minutes=30):
    df['event_timestamp'] = pd.to_datetime(df['event_timestamp'])
    
    df = df.sort_values(by=['user_pseudo_id', 'event_timestamp']).copy()
    
    errors = []

    for user_id, group in df.groupby('user_pseudo_id'):
        prev_time = None
        prev_session = None
        
        for idx, row in group.iterrows():
            curr_time = row['event_timestamp']
            curr_session = row['session_id']
            
            if prev_time is not None:
                time_diff = curr_time - prev_time
                
                if time_diff > pd.Timedelta(minutes=session_timeout_minutes):
                    if curr_session == prev_session:
                        errors.append({
                            'index': idx,
                            'user': user_id,
                            'prev_time': prev_time,
                            'curr_time': curr_time,
                            'time_diff': time_diff,
                            'session_error': 'Same session_id despite >30min gap'
                        })
                else:
                    if curr_session != prev_session:
                        errors.append({
                            'index': idx,
                            'user': user_id,
                            'prev_time': prev_time,
                            'curr_time': curr_time,
                            'time_diff': time_diff,
                            'session_error': 'Different session_id despite <=30min gap'
                        })

            prev_time = curr_time
            prev_session = curr_session

    if not errors:
        print("✅ All session_id assignments are correct.")
    else:
        print(f"❌ Found {len(errors)} session_id assignment issues.")
        return pd.DataFrame(errors)

error_df = validate_sessions(df)
if error_df is not None:
    error_df.head()

✅ All session_id assignments are correct.

In [39]:
df.to_csv('../CSV_output/sessionized_data.csv', index=False)

In [40]:
df.to_parquet('../parquet_output/sessionized_data.parquet', index=False)