In [2]:
import pandas as pd
import time 
import datetime

In [3]:
start_timestamp = time.time()

In [4]:
sessionized_df =pd.read_parquet("../parquet_output/sessionized_data.parquet")
sessionized_df.head()

             event_timestamp  user_pseudo_id          session_id
0 2024-11-14 05:54:51.907376   251617.173156  251617.173156369_1
1 2024-11-14 05:54:51.907376   251617.173156  251617.173156369_1
2 2024-11-14 05:54:51.907376   251617.173156  251617.173156369_1
3 2024-11-14 05:54:57.126554   251617.173156  251617.173156369_1
4 2024-11-14 05:55:08.384203   251617.173156  251617.173156369_1

In [5]:
df = sessionized_df
df

                  event_timestamp  user_pseudo_id            session_id
0      2024-11-14 05:54:51.907376    2.516172e+05    251617.173156369_1
1      2024-11-14 05:54:51.907376    2.516172e+05    251617.173156369_1
2      2024-11-14 05:54:51.907376    2.516172e+05    251617.173156369_1
3      2024-11-14 05:54:57.126554    2.516172e+05    251617.173156369_1
4      2024-11-14 05:55:08.384203    2.516172e+05    251617.173156369_1
...                           ...             ...                   ...
260859 2024-11-14 03:17:08.166826    2.145681e+09  2145680768.1731555_1
260860 2024-11-14 03:17:26.457025    2.145681e+09  2145680768.1731555_1
260861 2024-11-14 03:17:26.457025    2.145681e+09  2145680768.1731555_1
260862 2024-11-14 03:17:45.807694    2.145681e+09  2145680768.1731555_1
260863 2024-11-14 03:19:56.763039    2.145681e+09  2145680768.1731555_1

[260864 rows x 3 columns]

In [6]:
df['event_timestamp'] = pd.to_datetime(df['event_timestamp'])
df['event_date'] = df['event_timestamp'].dt.date

df

,event_timestamp,user_pseudo_id,session_id,event_date
0,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,2024-11-14
1,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,2024-11-14
2,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,2024-11-14
3,2024-11-14 05:54:57.126554,2.516172e+05,251617.173156369_1,2024-11-14
4,2024-11-14 05:55:08.384203,2.516172e+05,251617.173156369_1,2024-11-14
...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2.145681e+09,2145680768.1731555_1,2024-11-14
260860,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,2024-11-14
260861,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,2024-11-14
260862,2024-11-14 03:17:45.807694,2.145681e+09,2145680768.1731555_1,2024-11-14
260863,2024-11-14 03:19:56.763039,2.145681e+09,2145680768.1731555_1,2024-11-14

In [7]:
df['minutes_to_midnight'] = (
    pd.to_datetime(df['event_date']) + pd.Timedelta(days=1) - df['event_timestamp']
).dt.total_seconds() / 60

df

,event_timestamp,user_pseudo_id,session_id,event_date,minutes_to_midnight
0,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,2024-11-14,1085.134877
1,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,2024-11-14,1085.134877
2,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,2024-11-14,1085.134877
3,2024-11-14 05:54:57.126554,2.516172e+05,251617.173156369_1,2024-11-14,1085.047891
4,2024-11-14 05:55:08.384203,2.516172e+05,251617.173156369_1,2024-11-14,1084.860263
...,...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2.145681e+09,2145680768.1731555_1,2024-11-14,1242.863886
260860,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,2024-11-14,1242.559050
260861,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,2024-11-14,1242.559050
260862,2024-11-14 03:17:45.807694,2.145681e+09,2145680768.1731555_1,2024-11-14,1242.236538
260863,2024-11-14 03:19:56.763039,2.145681e+09,2145680768.1731555_1,2024-11-14,1240.053949

In [8]:
df.sort_values(by=['user_pseudo_id', 'event_date', 'event_timestamp'], inplace=True)

df

,event_timestamp,user_pseudo_id,session_id,event_date,minutes_to_midnight
0,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,2024-11-14,1085.134877
1,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,2024-11-14,1085.134877
2,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,2024-11-14,1085.134877
3,2024-11-14 05:54:57.126554,2.516172e+05,251617.173156369_1,2024-11-14,1085.047891
4,2024-11-14 05:55:08.384203,2.516172e+05,251617.173156369_1,2024-11-14,1084.860263
...,...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2.145681e+09,2145680768.1731555_1,2024-11-14,1242.863886
260860,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,2024-11-14,1242.559050
260861,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,2024-11-14,1242.559050
260862,2024-11-14 03:17:45.807694,2.145681e+09,2145680768.1731555_1,2024-11-14,1242.236538
260863,2024-11-14 03:19:56.763039,2.145681e+09,2145680768.1731555_1,2024-11-14,1240.053949

In [9]:
last_event_mask = ~df.duplicated(subset=['user_pseudo_id', 'event_date'], keep='last')
last_event_mask

0         False
1         False
2         False
3         False
4         False
          ...
260859    False
260860    False
260861    False
260862    False
260863     True
Length: 260864, dtype: bool

In [10]:
df['possible_next_day_session'] = False

In [11]:
df.loc[last_event_mask & (df['minutes_to_midnight'] <= 30), 'possible_next_day_session'] = True

In [12]:
df.drop(columns=['event_date', 'minutes_to_midnight'], inplace=True)

In [13]:
df

,event_timestamp,user_pseudo_id,session_id,possible_next_day_session
0,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False
1,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False
2,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False
3,2024-11-14 05:54:57.126554,2.516172e+05,251617.173156369_1,False
4,2024-11-14 05:55:08.384203,2.516172e+05,251617.173156369_1,False
...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2.145681e+09,2145680768.1731555_1,False
260860,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False
260861,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False
260862,2024-11-14 03:17:45.807694,2.145681e+09,2145680768.1731555_1,False
260863,2024-11-14 03:19:56.763039,2.145681e+09,2145680768.1731555_1,False

In [14]:
# last_event_indices = (
#     df.groupby(['user_pseudo_id', 'event_date'])['event_timestamp']
#     .idxmax()
# )

# last_event_indices

In [15]:
df['time_of_day'] = df['event_timestamp'].dt.time

In [16]:
df['event_date'] = df['event_timestamp'].dt.date
df['minutes_from_midnight'] = (
    df['event_timestamp'] - pd.to_datetime(df['event_date'])
).dt.total_seconds() / 60

In [17]:
first_event_indices = (
    df.groupby(['user_pseudo_id', 'event_date'])['event_timestamp']
    .idxmin()
)

In [18]:
df['possible_previous_day_session'] = False

In [19]:
df.loc[first_event_indices, 'possible_previous_day_session'] = (
    df.loc[first_event_indices, 'minutes_from_midnight'] <= 30
)

In [20]:
df

,event_timestamp,user_pseudo_id,session_id,possible_next_day_session,time_of_day,event_date,minutes_from_midnight,possible_previous_day_session
0,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,05:54:51.907376,2024-11-14,354.865123,False
1,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,05:54:51.907376,2024-11-14,354.865123,False
2,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,05:54:51.907376,2024-11-14,354.865123,False
3,2024-11-14 05:54:57.126554,2.516172e+05,251617.173156369_1,False,05:54:57.126554,2024-11-14,354.952109,False
4,2024-11-14 05:55:08.384203,2.516172e+05,251617.173156369_1,False,05:55:08.384203,2024-11-14,355.139737,False
...,...,...,...,...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2.145681e+09,2145680768.1731555_1,False,03:17:08.166826,2024-11-14,197.136114,False
260860,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,03:17:26.457025,2024-11-14,197.440950,False
260861,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,03:17:26.457025,2024-11-14,197.440950,False
260862,2024-11-14 03:17:45.807694,2.145681e+09,2145680768.1731555_1,False,03:17:45.807694,2024-11-14,197.763462,False
260863,2024-11-14 03:19:56.763039,2.145681e+09,2145680768.1731555_1,False,03:19:56.763039,2024-11-14,199.946051,False

In [21]:
df.drop(columns=['time_of_day', 'event_date', 'minutes_from_midnight'], inplace=True)

In [22]:
df

,event_timestamp,user_pseudo_id,session_id,possible_next_day_session,possible_previous_day_session
0,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False
1,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False
2,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False
3,2024-11-14 05:54:57.126554,2.516172e+05,251617.173156369_1,False,False
4,2024-11-14 05:55:08.384203,2.516172e+05,251617.173156369_1,False,False
...,...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2.145681e+09,2145680768.1731555_1,False,False
260860,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False
260861,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False
260862,2024-11-14 03:17:45.807694,2.145681e+09,2145680768.1731555_1,False,False
260863,2024-11-14 03:19:56.763039,2.145681e+09,2145680768.1731555_1,False,False

In [23]:
df = df.sort_values(['user_pseudo_id', 'event_timestamp'])
df

,event_timestamp,user_pseudo_id,session_id,possible_next_day_session,possible_previous_day_session
0,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False
1,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False
2,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False
3,2024-11-14 05:54:57.126554,2.516172e+05,251617.173156369_1,False,False
4,2024-11-14 05:55:08.384203,2.516172e+05,251617.173156369_1,False,False
...,...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2.145681e+09,2145680768.1731555_1,False,False
260860,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False
260861,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False
260862,2024-11-14 03:17:45.807694,2.145681e+09,2145680768.1731555_1,False,False
260863,2024-11-14 03:19:56.763039,2.145681e+09,2145680768.1731555_1,False,False

In [24]:
df['next_event_timestamp'] = df.groupby('user_pseudo_id')['event_timestamp'].shift(-1)
df

,event_timestamp,user_pseudo_id,session_id,possible_next_day_session,possible_previous_day_session,next_event_timestamp
0,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:54:51.907376
1,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:54:51.907376
2,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:54:57.126554
3,2024-11-14 05:54:57.126554,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:55:08.384203
4,2024-11-14 05:55:08.384203,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:55:08.384203
...,...,...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:17:26.457025
260860,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:17:26.457025
260861,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:17:45.807694
260862,2024-11-14 03:17:45.807694,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:19:56.763039
260863,2024-11-14 03:19:56.763039,2.145681e+09,2145680768.1731555_1,False,False,NaT

In [25]:
df['next_event_date'] = pd.to_datetime(df['next_event_timestamp'].dt.date)
df

,event_timestamp,user_pseudo_id,session_id,possible_next_day_session,possible_previous_day_session,next_event_timestamp,next_event_date
0,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:54:51.907376,2024-11-14
1,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:54:51.907376,2024-11-14
2,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:54:57.126554,2024-11-14
3,2024-11-14 05:54:57.126554,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:55:08.384203,2024-11-14
4,2024-11-14 05:55:08.384203,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:55:08.384203,2024-11-14
...,...,...,...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:17:26.457025,2024-11-14
260860,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:17:26.457025,2024-11-14
260861,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:17:45.807694,2024-11-14
260862,2024-11-14 03:17:45.807694,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:19:56.763039,2024-11-14
260863,2024-11-14 03:19:56.763039,2.145681e+09,2145680768.1731555_1,False,False,NaT,NaT

In [26]:
df['time_to_next_event'] = (df['next_event_timestamp'] - df['event_timestamp']).dt.total_seconds() / 60
df

,event_timestamp,user_pseudo_id,session_id,possible_next_day_session,possible_previous_day_session,next_event_timestamp,next_event_date,time_to_next_event
0,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:54:51.907376,2024-11-14,0.000000
1,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:54:51.907376,2024-11-14,0.000000
2,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:54:57.126554,2024-11-14,0.086986
3,2024-11-14 05:54:57.126554,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:55:08.384203,2024-11-14,0.187627
4,2024-11-14 05:55:08.384203,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:55:08.384203,2024-11-14,0.000000
...,...,...,...,...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:17:26.457025,2024-11-14,0.304837
260860,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:17:26.457025,2024-11-14,0.000000
260861,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:17:45.807694,2024-11-14,0.322511
260862,2024-11-14 03:17:45.807694,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:19:56.763039,2024-11-14,2.182589
260863,2024-11-14 03:19:56.763039,2.145681e+09,2145680768.1731555_1,False,False,NaT,NaT,NaN

In [27]:
df['is_next_day'] = df['next_event_date'] == (pd.to_datetime(df['event_timestamp'].dt.date) + pd.Timedelta(days=1))
df

,event_timestamp,user_pseudo_id,session_id,possible_next_day_session,possible_previous_day_session,next_event_timestamp,next_event_date,time_to_next_event,is_next_day
0,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:54:51.907376,2024-11-14,0.000000,False
1,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:54:51.907376,2024-11-14,0.000000,False
2,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:54:57.126554,2024-11-14,0.086986,False
3,2024-11-14 05:54:57.126554,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:55:08.384203,2024-11-14,0.187627,False
4,2024-11-14 05:55:08.384203,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:55:08.384203,2024-11-14,0.000000,False
...,...,...,...,...,...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:17:26.457025,2024-11-14,0.304837,False
260860,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:17:26.457025,2024-11-14,0.000000,False
260861,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:17:45.807694,2024-11-14,0.322511,False
260862,2024-11-14 03:17:45.807694,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:19:56.763039,2024-11-14,2.182589,False
260863,2024-11-14 03:19:56.763039,2.145681e+09,2145680768.1731555_1,False,False,NaT,NaT,NaN,False

In [28]:
cross_day_conditions = (
    df['possible_next_day_session'] & 
    df['possible_previous_day_session'].shift(-1).fillna(False) & 
     (df['time_to_next_event'] <= 30) & 
    df['is_next_day']
)

cross_day_conditions

C:\Users\aalig\AppData\Local\Temp\ipykernel_25288\2544222326.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['possible_previous_day_session'].shift(-1).fillna(False) &

0         False
1         False
2         False
3         False
4         False
          ...
260859    False
260860    False
260861    False
260862    False
260863    False
Length: 260864, dtype: bool

In [29]:
df['cross_day_session'] = False
df.loc[cross_day_conditions, 'cross_day_session'] = True
df.loc[cross_day_conditions.shift(1).fillna(False), 'cross_day_session'] = True
df

C:\Users\aalig\AppData\Local\Temp\ipykernel_25288\3186662669.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.loc[cross_day_conditions.shift(1).fillna(False), 'cross_day_session'] = True

,event_timestamp,user_pseudo_id,session_id,possible_next_day_session,possible_previous_day_session,next_event_timestamp,next_event_date,time_to_next_event,is_next_day,cross_day_session
0,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:54:51.907376,2024-11-14,0.000000,False,False
1,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:54:51.907376,2024-11-14,0.000000,False,False
2,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:54:57.126554,2024-11-14,0.086986,False,False
3,2024-11-14 05:54:57.126554,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:55:08.384203,2024-11-14,0.187627,False,False
4,2024-11-14 05:55:08.384203,2.516172e+05,251617.173156369_1,False,False,2024-11-14 05:55:08.384203,2024-11-14,0.000000,False,False
...,...,...,...,...,...,...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:17:26.457025,2024-11-14,0.304837,False,False
260860,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:17:26.457025,2024-11-14,0.000000,False,False
260861,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:17:45.807694,2024-11-14,0.322511,False,False
260862,2024-11-14 03:17:45.807694,2.145681e+09,2145680768.1731555_1,False,False,2024-11-14 03:19:56.763039,2024-11-14,2.182589,False,False
260863,2024-11-14 03:19:56.763039,2.145681e+09,2145680768.1731555_1,False,False,NaT,NaT,NaN,False,False

In [30]:
df.drop(['next_event_timestamp', 'next_event_date', 'time_to_next_event', 'is_next_day'], 
        axis=1, inplace=True)

In [31]:
df

,event_timestamp,user_pseudo_id,session_id,possible_next_day_session,possible_previous_day_session,cross_day_session
0,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,False
1,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,False
2,2024-11-14 05:54:51.907376,2.516172e+05,251617.173156369_1,False,False,False
3,2024-11-14 05:54:57.126554,2.516172e+05,251617.173156369_1,False,False,False
4,2024-11-14 05:55:08.384203,2.516172e+05,251617.173156369_1,False,False,False
...,...,...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2.145681e+09,2145680768.1731555_1,False,False,False
260860,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False,False
260861,2024-11-14 03:17:26.457025,2.145681e+09,2145680768.1731555_1,False,False,False
260862,2024-11-14 03:17:45.807694,2.145681e+09,2145680768.1731555_1,False,False,False
260863,2024-11-14 03:19:56.763039,2.145681e+09,2145680768.1731555_1,False,False,False

In [32]:
df.to_parquet('../parquet_output/sessionization_cross_day.parquet', index=False)

In [33]:
# ... your script ...
end_time = time.time()
print(f"Runtime of the script: {end_time - start_timestamp:.2f} seconds")

Runtime of the script: 2.99 seconds