In [19]:
import pandas as pd 
import uuid

In [20]:
df = pd.read_parquet('../ga4-clean/events-normalized/analytics291746817/2024/10/events_20241002.parquet')
df

,event_date,event_timestamp,event_name,event_previous_timestamp,event_value_in_usd,event_bundle_sequence_id,event_server_timestamp_offset,user_id,user_pseudo_id,user_first_touch_timestamp,...,ep_percent_scrolled,ep_click_text,ep_click_url,ep_ignore_referrer,ep_page_referrer,ep_campaign,ep_term,ep_click_classes,user_prop_user_client_id,user_prop_user_session_id
0,20241002,1.727878e+15,phone_call,None,None,-5.587334e+08,None,None,c669b94d-c57e-50f9-9996-4c45803fc949,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
1,20241002,1.727875e+15,phone_call,None,None,1.211234e+09,None,None,6752f4b9-512f-5159-9b0f-ee298555977c,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
2,20241002,1.727879e+15,phone_call,None,None,5.381634e+08,None,None,4a3fccda-98cd-5f7c-b397-bc6ff7e56c89,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
3,20241002,1.727894e+15,phone_call,None,None,-1.310882e+09,None,None,139872666.1724082962,1.724083e+15,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
4,20241002,1.727931e+15,session_start,None,None,1.434278e+09,None,None,903004489.1727851822,1.727852e+15,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13672,nan,NaN,nan,nan,nan,NaN,nan,nan,nan,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13673,nan,NaN,nan,nan,nan,NaN,nan,nan,nan,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13674,nan,NaN,nan,nan,nan,NaN,nan,nan,nan,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13675,nan,NaN,nan,nan,nan,NaN,nan,nan,nan,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13676,nan,NaN,nan,nan,nan,NaN,nan,nan,nan,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [21]:
df['event_timestamp'] = pd.to_datetime(df['event_timestamp'],unit='us')
df

,event_date,event_timestamp,event_name,event_previous_timestamp,event_value_in_usd,event_bundle_sequence_id,event_server_timestamp_offset,user_id,user_pseudo_id,user_first_touch_timestamp,...,ep_percent_scrolled,ep_click_text,ep_click_url,ep_ignore_referrer,ep_page_referrer,ep_campaign,ep_term,ep_click_classes,user_prop_user_client_id,user_prop_user_session_id
0,20241002,2024-10-02 14:00:14.000000,phone_call,None,None,-5.587334e+08,None,None,c669b94d-c57e-50f9-9996-4c45803fc949,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
1,20241002,2024-10-02 13:16:23.000000,phone_call,None,None,1.211234e+09,None,None,6752f4b9-512f-5159-9b0f-ee298555977c,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
2,20241002,2024-10-02 14:16:33.000000,phone_call,None,None,5.381634e+08,None,None,4a3fccda-98cd-5f7c-b397-bc6ff7e56c89,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
3,20241002,2024-10-02 18:32:54.000000,phone_call,None,None,-1.310882e+09,None,None,139872666.1724082962,1.724083e+15,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
4,20241002,2024-10-03 04:53:21.968005,session_start,None,None,1.434278e+09,None,None,903004489.1727851822,1.727852e+15,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13672,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13673,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13674,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13675,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13676,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [22]:
df = df.sort_values(['user_pseudo_id', 'event_timestamp'])
df

,event_date,event_timestamp,event_name,event_previous_timestamp,event_value_in_usd,event_bundle_sequence_id,event_server_timestamp_offset,user_id,user_pseudo_id,user_first_touch_timestamp,...,ep_percent_scrolled,ep_click_text,ep_click_url,ep_ignore_referrer,ep_page_referrer,ep_campaign,ep_term,ep_click_classes,user_prop_user_client_id,user_prop_user_session_id
1141,20241002,2024-10-02 19:42:42.286735,first_visit,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
1142,20241002,2024-10-02 19:42:42.286735,session_start,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,NaN,nan,nan,nan,https://thefaceloft.com/,nan,nan,nan,nan,nan
1143,20241002,2024-10-02 19:42:42.286735,page_view,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,NaN,nan,nan,true,nan,nan,nan,nan,nan,nan
1144,20241002,2024-10-02 19:42:47.015684,user_session_info,None,None,-1.535903e+09,None,None,1036715368.1727898162,1.727898e+15,...,NaN,nan,nan,nan,nan,nan,nan,nan,_1036715368.1727898162,_1727898161
1145,20241002,2024-10-02 19:42:47.015684,scroll,None,None,-1.535903e+09,None,None,1036715368.1727898162,1.727898e+15,...,50.0,nan,nan,nan,nan,nan,nan,nan,_1036715368.1727898162,_1727898161
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13672,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13673,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13674,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13675,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13676,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [23]:
session_timeout = pd.Timedelta(minutes=30)

In [24]:
df['previous_timestamp'] = df.groupby(['user_pseudo_id'])['event_timestamp'].shift()
df

,event_date,event_timestamp,event_name,event_previous_timestamp,event_value_in_usd,event_bundle_sequence_id,event_server_timestamp_offset,user_id,user_pseudo_id,user_first_touch_timestamp,...,ep_click_text,ep_click_url,ep_ignore_referrer,ep_page_referrer,ep_campaign,ep_term,ep_click_classes,user_prop_user_client_id,user_prop_user_session_id,previous_timestamp
1141,20241002,2024-10-02 19:42:42.286735,first_visit,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT
1142,20241002,2024-10-02 19:42:42.286735,session_start,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,https://thefaceloft.com/,nan,nan,nan,nan,nan,2024-10-02 19:42:42.286735
1143,20241002,2024-10-02 19:42:42.286735,page_view,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,true,nan,nan,nan,nan,nan,nan,2024-10-02 19:42:42.286735
1144,20241002,2024-10-02 19:42:47.015684,user_session_info,None,None,-1.535903e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,nan,nan,nan,_1036715368.1727898162,_1727898161,2024-10-02 19:42:42.286735
1145,20241002,2024-10-02 19:42:47.015684,scroll,None,None,-1.535903e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,nan,nan,nan,_1036715368.1727898162,_1727898161,2024-10-02 19:42:47.015684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13672,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT
13673,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT
13674,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT
13675,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT
13676,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaT

In [25]:
df['time_diff'] = pd.to_datetime(df['event_timestamp']) - pd.to_datetime(df['previous_timestamp'])
df

,event_date,event_timestamp,event_name,event_previous_timestamp,event_value_in_usd,event_bundle_sequence_id,event_server_timestamp_offset,user_id,user_pseudo_id,user_first_touch_timestamp,...,ep_click_url,ep_ignore_referrer,ep_page_referrer,ep_campaign,ep_term,ep_click_classes,user_prop_user_client_id,user_prop_user_session_id,previous_timestamp,time_diff
1141,20241002,2024-10-02 19:42:42.286735,first_visit,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,nan,nan,nan,nan,NaT,NaT
1142,20241002,2024-10-02 19:42:42.286735,session_start,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,https://thefaceloft.com/,nan,nan,nan,nan,nan,2024-10-02 19:42:42.286735,0 days 00:00:00
1143,20241002,2024-10-02 19:42:42.286735,page_view,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,true,nan,nan,nan,nan,nan,nan,2024-10-02 19:42:42.286735,0 days 00:00:00
1144,20241002,2024-10-02 19:42:47.015684,user_session_info,None,None,-1.535903e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,nan,nan,_1036715368.1727898162,_1727898161,2024-10-02 19:42:42.286735,0 days 00:00:04.728949
1145,20241002,2024-10-02 19:42:47.015684,scroll,None,None,-1.535903e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,nan,nan,_1036715368.1727898162,_1727898161,2024-10-02 19:42:47.015684,0 days 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13672,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,NaT,NaT
13673,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,NaT,NaT
13674,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,NaT,NaT
13675,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,NaT,NaT
13676,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,NaT,NaT

In [26]:
df['new_session'] = (df['time_diff'] > session_timeout) | (df['previous_timestamp'].isnull())
df

,event_date,event_timestamp,event_name,event_previous_timestamp,event_value_in_usd,event_bundle_sequence_id,event_server_timestamp_offset,user_id,user_pseudo_id,user_first_touch_timestamp,...,ep_ignore_referrer,ep_page_referrer,ep_campaign,ep_term,ep_click_classes,user_prop_user_client_id,user_prop_user_session_id,previous_timestamp,time_diff,new_session
1141,20241002,2024-10-02 19:42:42.286735,first_visit,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,nan,nan,nan,NaT,NaT,True
1142,20241002,2024-10-02 19:42:42.286735,session_start,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,https://thefaceloft.com/,nan,nan,nan,nan,nan,2024-10-02 19:42:42.286735,0 days 00:00:00,False
1143,20241002,2024-10-02 19:42:42.286735,page_view,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,true,nan,nan,nan,nan,nan,nan,2024-10-02 19:42:42.286735,0 days 00:00:00,False
1144,20241002,2024-10-02 19:42:47.015684,user_session_info,None,None,-1.535903e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,nan,_1036715368.1727898162,_1727898161,2024-10-02 19:42:42.286735,0 days 00:00:04.728949,False
1145,20241002,2024-10-02 19:42:47.015684,scroll,None,None,-1.535903e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,nan,_1036715368.1727898162,_1727898161,2024-10-02 19:42:47.015684,0 days 00:00:00,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13672,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,NaT,NaT,True
13673,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,NaT,NaT,True
13674,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,NaT,NaT,True
13675,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,NaT,NaT,True
13676,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,NaT,NaT,True

In [27]:
df['session_id'] = df.groupby('user_pseudo_id')['new_session'].cumsum()
df

,event_date,event_timestamp,event_name,event_previous_timestamp,event_value_in_usd,event_bundle_sequence_id,event_server_timestamp_offset,user_id,user_pseudo_id,user_first_touch_timestamp,...,ep_page_referrer,ep_campaign,ep_term,ep_click_classes,user_prop_user_client_id,user_prop_user_session_id,previous_timestamp,time_diff,new_session,session_id
1141,20241002,2024-10-02 19:42:42.286735,first_visit,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,nan,nan,NaT,NaT,True,1
1142,20241002,2024-10-02 19:42:42.286735,session_start,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,https://thefaceloft.com/,nan,nan,nan,nan,nan,2024-10-02 19:42:42.286735,0 days 00:00:00,False,1
1143,20241002,2024-10-02 19:42:42.286735,page_view,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,nan,nan,2024-10-02 19:42:42.286735,0 days 00:00:00,False,1
1144,20241002,2024-10-02 19:42:47.015684,user_session_info,None,None,-1.535903e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,_1036715368.1727898162,_1727898161,2024-10-02 19:42:42.286735,0 days 00:00:04.728949,False,1
1145,20241002,2024-10-02 19:42:47.015684,scroll,None,None,-1.535903e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,_1036715368.1727898162,_1727898161,2024-10-02 19:42:47.015684,0 days 00:00:00,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13672,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,NaT,NaT,True,12475
13673,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,NaT,NaT,True,12476
13674,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,NaT,NaT,True,12477
13675,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,NaT,NaT,True,12478
13676,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,NaT,NaT,True,12479

In [28]:
df['session_id'] = df['new_session'].apply(lambda x: str(uuid.uuid4()) if x else None)
df['session_id'] = df.groupby('user_pseudo_id')['session_id'].ffill()

In [29]:
df.drop(columns=['previous_timestamp', 'time_diff', 'new_session'], inplace=True)

In [30]:
df

,event_date,event_timestamp,event_name,event_previous_timestamp,event_value_in_usd,event_bundle_sequence_id,event_server_timestamp_offset,user_id,user_pseudo_id,user_first_touch_timestamp,...,ep_click_text,ep_click_url,ep_ignore_referrer,ep_page_referrer,ep_campaign,ep_term,ep_click_classes,user_prop_user_client_id,user_prop_user_session_id,session_id
1141,20241002,2024-10-02 19:42:42.286735,first_visit,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,f828c1bd-7ef5-46be-b2ea-4fc8595b1657
1142,20241002,2024-10-02 19:42:42.286735,session_start,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,https://thefaceloft.com/,nan,nan,nan,nan,nan,f828c1bd-7ef5-46be-b2ea-4fc8595b1657
1143,20241002,2024-10-02 19:42:42.286735,page_view,None,None,-1.540632e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,true,nan,nan,nan,nan,nan,nan,f828c1bd-7ef5-46be-b2ea-4fc8595b1657
1144,20241002,2024-10-02 19:42:47.015684,user_session_info,None,None,-1.535903e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,nan,nan,nan,_1036715368.1727898162,_1727898161,f828c1bd-7ef5-46be-b2ea-4fc8595b1657
1145,20241002,2024-10-02 19:42:47.015684,scroll,None,None,-1.535903e+09,None,None,1036715368.1727898162,1.727898e+15,...,nan,nan,nan,nan,nan,nan,nan,_1036715368.1727898162,_1727898161,f828c1bd-7ef5-46be-b2ea-4fc8595b1657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13672,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,2d29c50c-dd2b-4409-9d8c-9d4060e7459f
13673,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,3fdf96c5-f552-4fa1-91ea-cd0ea9c7d3c0
13674,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,94e97cc8-61e5-4197-a2dc-03856649ae4c
13675,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,90e53c42-c45d-464b-8ba4-9edaf3e21a30
13676,nan,NaT,nan,nan,nan,NaN,nan,nan,nan,NaN,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,0ffe31b8-2c56-4afb-bca4-5f53ad432843

In [ ]:
cols = list(df.columns)

cols.insert(cols.index('event_timestamp') + 1, cols.pop(cols.index('session_id')))

df = df[cols]

In [32]:
df

,event_date,event_timestamp,session_id,event_name,event_previous_timestamp,event_value_in_usd,event_bundle_sequence_id,event_server_timestamp_offset,user_id,user_pseudo_id,...,ep_percent_scrolled,ep_click_text,ep_click_url,ep_ignore_referrer,ep_page_referrer,ep_campaign,ep_term,ep_click_classes,user_prop_user_client_id,user_prop_user_session_id
1141,20241002,2024-10-02 19:42:42.286735,f828c1bd-7ef5-46be-b2ea-4fc8595b1657,first_visit,None,None,-1.540632e+09,None,None,1036715368.1727898162,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
1142,20241002,2024-10-02 19:42:42.286735,f828c1bd-7ef5-46be-b2ea-4fc8595b1657,session_start,None,None,-1.540632e+09,None,None,1036715368.1727898162,...,NaN,nan,nan,nan,https://thefaceloft.com/,nan,nan,nan,nan,nan
1143,20241002,2024-10-02 19:42:42.286735,f828c1bd-7ef5-46be-b2ea-4fc8595b1657,page_view,None,None,-1.540632e+09,None,None,1036715368.1727898162,...,NaN,nan,nan,true,nan,nan,nan,nan,nan,nan
1144,20241002,2024-10-02 19:42:47.015684,f828c1bd-7ef5-46be-b2ea-4fc8595b1657,user_session_info,None,None,-1.535903e+09,None,None,1036715368.1727898162,...,NaN,nan,nan,nan,nan,nan,nan,nan,_1036715368.1727898162,_1727898161
1145,20241002,2024-10-02 19:42:47.015684,f828c1bd-7ef5-46be-b2ea-4fc8595b1657,scroll,None,None,-1.535903e+09,None,None,1036715368.1727898162,...,50.0,nan,nan,nan,nan,nan,nan,nan,_1036715368.1727898162,_1727898161
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13672,nan,NaT,2d29c50c-dd2b-4409-9d8c-9d4060e7459f,nan,nan,nan,NaN,nan,nan,nan,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13673,nan,NaT,3fdf96c5-f552-4fa1-91ea-cd0ea9c7d3c0,nan,nan,nan,NaN,nan,nan,nan,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13674,nan,NaT,94e97cc8-61e5-4197-a2dc-03856649ae4c,nan,nan,nan,NaN,nan,nan,nan,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13675,nan,NaT,90e53c42-c45d-464b-8ba4-9edaf3e21a30,nan,nan,nan,NaN,nan,nan,nan,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan
13676,nan,NaT,0ffe31b8-2c56-4afb-bca4-5f53ad432843,nan,nan,nan,NaN,nan,nan,nan,...,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [33]:
df['session_id'].value_counts()

session_id
9796a69f-cb46-4cc7-856e-680a37b1e35c    74
0bc3785b-9e8f-4e8d-924f-9441c7afea61    60
b1058c89-4c86-4ec0-9f25-b919f45cc5a2    54
68bc0448-615d-4343-be74-6d9726d52a4d    52
604f760a-26e6-437a-91f0-dc7760a8fc33    44
                                        ..
f6afa70f-a6fa-4252-ba1c-841a35b8f212     1
8f9e741f-13dd-4d3e-88e3-84aa2d559382     1
74a376fa-52c2-4565-acb1-641a24737ba4     1
b71aedb1-dc6e-4694-952f-1835c08a7555     1
8d8ea97e-aaff-4ff0-bd02-275500cd7e57     1
Name: count, Length: 12557, dtype: int64

In [34]:
df['session_id'].nunique()

12557