In [2]:
import pandas as pd 
import uuid

In [10]:
df = pd.read_parquet('../ga4-clean/session-identifier/analytics291746817/2024/10/events_session_identifier.parquet')
df

,event_date,event_timestamp,session_id,event_name,event_previous_timestamp,event_value_in_usd,event_bundle_sequence_id,event_server_timestamp_offset,user_id,user_pseudo_id,...,session_traffic_source_last_click_cm360_campaign_creative_name,session_traffic_source_last_click_cm360_campaign_creative_type,session_traffic_source_last_click_cm360_campaign_creative_type_id,session_traffic_source_last_click_cm360_campaign_creative_version,session_traffic_source_last_click_cm360_campaign_placement_id,session_traffic_source_last_click_cm360_campaign_placement_cost_structure,session_traffic_source_last_click_cm360_campaign_placement_name,session_traffic_source_last_click_cm360_campaign_rendering_id,session_traffic_source_last_click_cm360_campaign_site_id,session_traffic_source_last_click_cm360_campaign_site_name
0,20241025,2024-10-25 15:08:58,272a56a4-48ad-4755-bc7b-3153efad3b34,phone_call,None,None,-2032081077,None,None,02e13a03-78c4-5060-9759-d729b2ee5ed6,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set)
1,20241028,2024-10-28 14:46:21,272f5c26-1d11-41e7-9223-6e04c1241bbe,phone_call,None,None,-1894611157,None,None,02e13a03-78c4-5060-9759-d729b2ee5ed6,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set)
2,20241029,2024-10-29 17:32:20,2730baff-6273-4b28-9572-cb826f8942eb,phone_call,None,None,211065839,None,None,041080cd-481a-51fe-909d-db55d64c6bc2,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set)
3,20241018,2024-10-18 15:25:18,9ae86b68-49a4-472e-b195-1d78b4fb0a8a,phone_call,None,None,-91792395,None,None,05ad3c2f-3cb0-5cec-bfbd-9d18cf1b914a,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set)
4,20241018,2024-10-18 15:43:44,9ae86b68-49a4-472e-b195-1d78b4fb0a8a,phone_call,None,None,925628956,None,None,05ad3c2f-3cb0-5cec-bfbd-9d18cf1b914a,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27581,20241021,2024-10-21 20:57:58,537ec84f-f8a6-405f-a0a1-b76ade29879c,phone_call,None,None,-281774010,None,None,fb423390-eca1-5ce0-bd27-85d7d3955074,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set)
27582,20241023,2024-10-23 14:43:57,b7421757-9619-4aa0-8576-2500c252addc,phone_call,None,None,-233212911,None,None,fb423390-eca1-5ce0-bd27-85d7d3955074,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set)
27583,20241031,2024-10-31 19:09:00,d3da0409-7d7b-4364-b1f5-e3c7e6664295,phone_call,None,None,-1732551840,None,None,fd10e10e-140b-58d1-835c-050a2d8e9f30,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set)
27584,20241011,2024-10-11 19:01:58,7c421bc8-4609-48e6-b2db-57ffb494636a,phone_call,None,None,653001345,None,None,feb03477-a3cb-582e-bad4-8712894bae05,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set)
27585,20241009,2024-10-09 19:12:11,57063efd-417c-4017-b721-1f63af458058,phone_call,None,None,292524927,None,None,ff395d89-4a3c-5649-918e-fdd23d38f60e,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set)

In [11]:
groupby_df = df.groupby("session_id").agg(
    total_events=("session_id", "count"),                    # count of events in session
    first_event=("event_timestamp", "min"),                  # session start
    last_event=("event_timestamp", "max"),                   # session end
    session_duration=("event_timestamp", lambda x: x.max() - x.min()),
    unique_pages=("ep_page_location", "nunique"),            # how many unique pages
    first_page=("ep_page_location", "first"),                # first page visited
    last_page=("ep_page_location", "last")                   # last page visited
).reset_index()

groupby_df

,session_id,total_events,first_event,last_event,session_duration,unique_pages,first_page,last_page
0,00268b04-c3e3-4be6-9844-300e8a729ffe,2,2024-10-16 11:09:08.946430,2024-10-16 11:09:08.946430,0 days 00:00:00,1,https://thefaceloft.com/links/,https://thefaceloft.com/links/
1,005f0af5-0389-478b-a2d0-685212613476,12,2024-10-15 21:06:26.131316,2024-10-15 21:08:10.406916,0 days 00:01:44.275600,2,https://thefaceloft.com/?utm_source=OffSite&ut...,https://thefaceloft.com/dermal-fillers/
2,007f106f-6a89-4795-9136-b9ad4c78a0e5,4,2024-10-23 21:56:49.879182,2024-10-23 21:56:56.028690,0 days 00:00:06.149508,1,https://thefaceloft.com/laser-treatments/,https://thefaceloft.com/laser-treatments/
3,008a5463-5293-47cb-abe0-835b726aac67,11,2024-10-17 00:13:57.743014,2024-10-17 00:14:19.638017,0 days 00:00:21.895003,1,https://thefaceloft.com/b-12-injections/,https://thefaceloft.com/b-12-injections/
4,008bbf77-1aa5-41cc-bc15-120e4c3fad42,22,2024-10-26 13:39:15.509800,2024-10-26 13:55:42.053205,0 days 00:16:26.543405,2,https://thefaceloft.com/shop/,https://thefaceloft.com/laser-treatments/
...,...,...,...,...,...,...,...,...
1937,ff5c03eb-3313-430a-9b95-57a06473dd6c,13,2024-10-22 02:46:15.705085,2024-10-22 02:46:45.016898,0 days 00:00:29.311813,2,https://thefaceloft.com/?utm_source=OffSite&ut...,https://thefaceloft.com/skin-rejuvenation/
1938,ff756fa8-a402-4994-b7a3-04bbe0521410,5,2024-10-12 11:18:56.089361,2024-10-12 11:18:58.107614,0 days 00:00:02.018253,1,https://thefaceloft.com/?utm_source=OffSite&ut...,https://thefaceloft.com/?utm_source=OffSite&ut...
1939,ffc0a011-3521-4483-b70d-2dc6d195c60c,7,2024-10-19 13:39:09.844303,2024-10-19 13:41:49.615373,0 days 00:02:39.771070,1,https://thefaceloft.com/?utm_source=OffSite&ut...,https://thefaceloft.com/?utm_source=OffSite&ut...
1940,ffc9036e-45b1-41db-80f6-1df84538e27d,9,2024-10-12 19:55:01.428496,2024-10-12 19:55:06.720892,0 days 00:00:05.292396,1,https://thefaceloft.com/pdo-threads/,https://thefaceloft.com/pdo-threads/
1941,ffda151f-c4fa-408d-933c-95ac5ae3a567,37,2024-10-22 12:02:33.636003,2024-10-22 12:18:36.510456,0 days 00:16:02.874453,3,https://thefaceloft.com/?utm_source=OffSite&ut...,https://thefaceloft.com/request-appointment/

In [ ]:
df["is_missing"] = (
    df["ep_page_location"].isna() |
    (df['ep_page_location']=='None')
    (df["ep_page_location"] == "")
)
df

,event_date,event_timestamp,session_id,event_name,event_previous_timestamp,event_value_in_usd,event_bundle_sequence_id,event_server_timestamp_offset,user_id,user_pseudo_id,...,session_traffic_source_last_click_cm360_campaign_creative_type,session_traffic_source_last_click_cm360_campaign_creative_type_id,session_traffic_source_last_click_cm360_campaign_creative_version,session_traffic_source_last_click_cm360_campaign_placement_id,session_traffic_source_last_click_cm360_campaign_placement_cost_structure,session_traffic_source_last_click_cm360_campaign_placement_name,session_traffic_source_last_click_cm360_campaign_rendering_id,session_traffic_source_last_click_cm360_campaign_site_id,session_traffic_source_last_click_cm360_campaign_site_name,is_missing
0,20241025,2024-10-25 15:08:58,272a56a4-48ad-4755-bc7b-3153efad3b34,phone_call,None,None,-2032081077,None,None,02e13a03-78c4-5060-9759-d729b2ee5ed6,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),False
1,20241028,2024-10-28 14:46:21,272f5c26-1d11-41e7-9223-6e04c1241bbe,phone_call,None,None,-1894611157,None,None,02e13a03-78c4-5060-9759-d729b2ee5ed6,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),False
2,20241029,2024-10-29 17:32:20,2730baff-6273-4b28-9572-cb826f8942eb,phone_call,None,None,211065839,None,None,041080cd-481a-51fe-909d-db55d64c6bc2,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),False
3,20241018,2024-10-18 15:25:18,9ae86b68-49a4-472e-b195-1d78b4fb0a8a,phone_call,None,None,-91792395,None,None,05ad3c2f-3cb0-5cec-bfbd-9d18cf1b914a,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),False
4,20241018,2024-10-18 15:43:44,9ae86b68-49a4-472e-b195-1d78b4fb0a8a,phone_call,None,None,925628956,None,None,05ad3c2f-3cb0-5cec-bfbd-9d18cf1b914a,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27581,20241021,2024-10-21 20:57:58,537ec84f-f8a6-405f-a0a1-b76ade29879c,phone_call,None,None,-281774010,None,None,fb423390-eca1-5ce0-bd27-85d7d3955074,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),False
27582,20241023,2024-10-23 14:43:57,b7421757-9619-4aa0-8576-2500c252addc,phone_call,None,None,-233212911,None,None,fb423390-eca1-5ce0-bd27-85d7d3955074,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),False
27583,20241031,2024-10-31 19:09:00,d3da0409-7d7b-4364-b1f5-e3c7e6664295,phone_call,None,None,-1732551840,None,None,fd10e10e-140b-58d1-835c-050a2d8e9f30,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),False
27584,20241011,2024-10-11 19:01:58,7c421bc8-4609-48e6-b2db-57ffb494636a,phone_call,None,None,653001345,None,None,feb03477-a3cb-582e-bad4-8712894bae05,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),False
27585,20241009,2024-10-09 19:12:11,57063efd-417c-4017-b721-1f63af458058,phone_call,None,None,292524927,None,None,ff395d89-4a3c-5649-918e-fdd23d38f60e,...,(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),(not set),False