In [1]:
import pandas as pd
import sys
import os
sys.path.append(os.path.abspath('..'))
from Utility.MappingRules import MappingRules
from Utility.BuildTable import build_table,groupby_sessions,groupby_pageview,groupby_events
import time

In [2]:
start_time = time.time()

In [3]:
connection = MappingRules(
    host="localhost",
    user="root",
    password="1234",
    database="ga4_db"
)

mapping_rules = connection.build_rules()

✅ Connected to MariaDB

In [4]:
# query = """
#         SELECT
#             tf.id,
#             tf.title as field_title,
#             mt.title,
#             tf.field_priority,
#             ep.event_name,
#             ep.ep
#         FROM
#             ga4_org_model_table_fields tf
#         LEFT JOIN ga4_org_model_tables mt 
#             ON tf.associated_table_id = mt.id
#         LEFT JOIN ga4_org_model_event_parameters_types ept 
#             ON tf.id = ept.table_field_id
#         LEFT JOIN ga4_model_event_parameters ep 
#             ON ept.id = ep.event_parameter_type_id;
#         """

initial events data after normalization and creating sessions,pageviews identifier

In [5]:
df = pd.read_parquet('../../Google Analytics Data/parquet_output/events_event_identifier.parquet')

creates a dataframe with the columns define is mapping_rules

In [6]:
sessions_df = build_table(df, mapping_rules, 'Sessions')
sessions_df

,event_timestamp,year,month,event_name,session_id,Stream ID,Platform,User ID,User Pseudo ID,Event Date,...,Geo - Metro,Google Ads - Campaign,Google Ads - Account Name,Google Ads - Ad Group ID,Google Ads - Ad Group Name,Google Ads - Campaign ID,Google Ads - Campaign Name,Google Ads - Customer ID,Engagement Time Msec,Landing Page Title
0,2024-11-14 05:54:51.907376,2024,11,first_visit,56b4c156-3b3b-449f-8db0-18dfb3936d53,2211965939,WEB,NaN,251617.173156,20241113,...,Raleigh-Durham (Fayetteville) NC,NaN,None,None,None,None,None,None,None,None
1,2024-11-14 05:54:51.907376,2024,11,session_start,56b4c156-3b3b-449f-8db0-18dfb3936d53,2211965939,WEB,NaN,251617.173156,20241113,...,Raleigh-Durham (Fayetteville) NC,NaN,None,None,None,None,None,None,NaN,Shopko Optical Eye Care and Vision Centers
2,2024-11-14 05:54:51.907376,2024,11,page_view,56b4c156-3b3b-449f-8db0-18dfb3936d53,2211965939,WEB,NaN,251617.173156,20241113,...,Raleigh-Durham (Fayetteville) NC,NaN,None,None,None,None,None,None,None,None
3,2024-11-14 05:54:57.126554,2024,11,user_session_info,56b4c156-3b3b-449f-8db0-18dfb3936d53,2211965939,WEB,NaN,251617.173156,20241113,...,Raleigh-Durham (Fayetteville) NC,NaN,None,None,None,None,None,None,26.0,Shopko Optical Eye Care and Vision Centers
4,2024-11-14 05:55:08.384203,2024,11,scroll,56b4c156-3b3b-449f-8db0-18dfb3936d53,2211965939,WEB,NaN,251617.173156,20241113,...,Raleigh-Durham (Fayetteville) NC,NaN,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2024,11,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,2211965939,WEB,NaN,2145680768.173156,20241113,...,Omaha NE,NaN,None,None,None,None,None,None,None,None
260860,2024-11-14 03:17:26.457025,2024,11,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,2211965939,WEB,NaN,2145680768.173156,20241113,...,Omaha NE,NaN,None,None,None,None,None,None,None,None
260861,2024-11-14 03:17:26.457025,2024,11,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,2211965939,WEB,NaN,2145680768.173156,20241113,...,Omaha NE,NaN,None,None,None,None,None,None,None,None
260862,2024-11-14 03:17:45.807694,2024,11,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,2211965939,WEB,NaN,2145680768.173156,20241113,...,Omaha NE,NaN,None,None,None,None,None,None,None,None
260863,2024-11-14 03:19:56.763039,2024,11,user_engagement,df966189-a01b-4b3c-abe7-7d6b5481a98c,2211965939,WEB,NaN,2145680768.173156,20241113,...,Omaha NE,NaN,None,None,None,None,None,None,None,None

group by sessions_df

In [7]:
groupby_sessions = groupby_sessions(sessions_df)
groupby_sessions

,session_id,session_start_time,session_end_time,total_events,year,month,event_name,Stream ID,Platform,User ID,...,Geo - Metro,Google Ads - Campaign,Google Ads - Account Name,Google Ads - Ad Group ID,Google Ads - Ad Group Name,Google Ads - Campaign ID,Google Ads - Campaign Name,Google Ads - Customer ID,Engagement Time Msec,Landing Page Title
0,000d973d-83e3-44f5-9de6-334db09e4f9a,2024-11-13 17:03:25.462610,2024-11-13 17:03:44.159263,11,2024,11,first_visit,2211965939,WEB,None,...,Chicago IL,None,Shopko Optical,145629888860,VSP/Insurance,19425201491,Shopko Optical | Base Support,1488945470,11.0,Insurance and Vision Plans Accepted | Shopko O...
1,00119162-b7ad-435e-a0ca-de939a89859f,2024-11-13 17:18:23.100730,2024-11-13 17:19:55.568856,19,2024,11,first_visit,2211965939,WEB,None,...,Rochester-Mason City-Austin IA,None,None,None,None,None,None,None,47.0,Eye Exam Center Locations Near You
2,006223fb-a912-462a-ac58-8a4911b7b9f5,2024-11-14 02:14:00.940303,2024-11-14 02:14:00.940303,2,2024,11,session_start,2211965939,WEB,None,...,Wausau-Rhinelander WI,None,None,None,None,None,None,None,None,Shop Frames & Prescription Eyeglasses | Shopko...
3,006eec1d-66e4-4ae6-a5a1-65dcfc12f96f,2024-11-13 21:51:06.602663,2024-11-13 21:51:57.431919,20,2024,11,first_visit,2211965939,WEB,None,...,Lincoln & Hastings-Kearney NE,None,Shopko Optical,(not set),(not set),21768569725,Q4 P-Max Campaign 2024,1488945470,9.0,Eye Care Center in Grand Island - Shopko Optical
4,00726133-3efe-43e7-b45a-7af493cac2b6,2024-11-13 18:18:48.605186,2024-11-13 18:19:04.607177,13,2024,11,first_visit,2211965939,WEB,None,...,Des Moines-Ames IA,None,Shopko Optical,(not set),(not set),21768569725,Q4 P-Max Campaign 2024,1488945470,92.0,Eye Doctors in Watertown - Shopko Optical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5555,ffbfaba8-ffef-4730-b722-f1363f7df934,2024-11-14 01:54:07.577148,2024-11-14 01:54:13.144119,4,2024,11,first_visit,2211965939,WEB,None,...,Milwaukee WI,None,None,None,None,None,None,None,104.0,Shop Frames & Prescription Eyeglasses | Shopko...
5556,ffcbff4b-d1e5-4859-bb17-7e63c320f5cf,2024-11-14 02:01:10.557225,2024-11-14 02:02:48.205733,11,2024,11,session_start,2211965939,WEB,None,...,La Crosse-Eau Claire WI,None,None,None,None,None,None,None,80.0,Shop Frames & Prescription Eyeglasses | Shopko...
5557,ffd43911-1241-4dcf-99df-e3a5925b8ae5,2024-11-13 14:17:32.975595,2024-11-13 14:17:47.102549,12,2024,11,first_visit,2211965939,WEB,None,...,Chicago IL,None,None,None,None,None,None,None,108.0,Eye Care Center in Rochester - Shopko Optical
5558,ffd80398-8309-44aa-8a26-ddc31c4aa90d,2024-11-13 19:51:22.538294,2024-11-13 19:53:32.574955,28,2024,11,first_visit,2211965939,WEB,None,...,Denver CO,None,None,None,None,None,None,None,22.0,Eye Care Center in Norfolk - Shopko Optical
5559,fffcc089-4bfd-4d88-b1da-2f828f6a0bd0,2024-11-13 16:02:59.615590,2024-11-13 16:08:26.452638,52,2024,11,first_visit,2211965939,WEB,None,...,Mankato MN,None,None,None,None,None,None,None,19.0,Eye Care Center in Fairmont - Shopko Optical

In [8]:
pageview_df = build_table(df, mapping_rules, 'Pageviews')
pageview_df

,event_timestamp,year,month,event_name,session_id,pageview_id,Device - Advertising ID,Device - Browser,Device - Browser Version,Device - Category,...,Geo - City,Geo - Continent,Geo - Country,Geo - Metro,Geo - Region,Geo - Sub Continent,Page URL,Engagement Time Msec,Page Title,Page Referrer
0,2024-11-14 05:54:51.907376,2024,11,first_visit,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,NaN,NaN,NaN,desktop,...,Boydton,Americas,United States,Raleigh-Durham (Fayetteville) NC,Virginia,Northern America,None,None,None,None
1,2024-11-14 05:54:51.907376,2024,11,session_start,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,NaN,NaN,NaN,desktop,...,Boydton,Americas,United States,Raleigh-Durham (Fayetteville) NC,Virginia,Northern America,None,None,None,None
2,2024-11-14 05:54:51.907376,2024,11,page_view,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,NaN,NaN,NaN,desktop,...,Boydton,Americas,United States,Raleigh-Durham (Fayetteville) NC,Virginia,Northern America,https://www.shopko.com/,NaN,Shopko Optical Eye Care and Vision Centers,None
3,2024-11-14 05:54:57.126554,2024,11,user_session_info,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,NaN,NaN,NaN,desktop,...,Boydton,Americas,United States,Raleigh-Durham (Fayetteville) NC,Virginia,Northern America,None,None,None,None
4,2024-11-14 05:55:08.384203,2024,11,scroll,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,NaN,NaN,NaN,desktop,...,Boydton,Americas,United States,Raleigh-Durham (Fayetteville) NC,Virginia,Northern America,None,None,Shopko Optical Eye Care and Vision Centers,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2024,11,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,NaN,NaN,NaN,desktop,...,Bellevue,Americas,United States,Omaha NE,Nebraska,Northern America,None,None,Eye Care Center in Bellevue - Shopko Optical,https://www.google.com/
260860,2024-11-14 03:17:26.457025,2024,11,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,NaN,NaN,NaN,desktop,...,Bellevue,Americas,United States,Omaha NE,Nebraska,Northern America,None,None,Eye Care Center in Bellevue - Shopko Optical,https://www.google.com/
260861,2024-11-14 03:17:26.457025,2024,11,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,NaN,NaN,NaN,desktop,...,Bellevue,Americas,United States,Omaha NE,Nebraska,Northern America,None,None,Eye Care Center in Bellevue - Shopko Optical,https://www.google.com/
260862,2024-11-14 03:17:45.807694,2024,11,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,NaN,NaN,NaN,desktop,...,Bellevue,Americas,United States,Omaha NE,Nebraska,Northern America,None,None,Eye Care Center in Bellevue - Shopko Optical,https://www.google.com/
260863,2024-11-14 03:19:56.763039,2024,11,user_engagement,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,NaN,NaN,NaN,desktop,...,Bellevue,Americas,United States,Omaha NE,Nebraska,Northern America,None,None,Eye Care Center in Bellevue - Shopko Optical,https://www.google.com/

In [9]:
groupby_pageview = groupby_pageview(pageview_df)
groupby_pageview

,pageview_id,pageview_start_time,pageview_end_time,total_events,year,month,event_name,session_id,Device - Advertising ID,Device - Browser,...,Geo - City,Geo - Continent,Geo - Country,Geo - Metro,Geo - Region,Geo - Sub Continent,Page URL,Engagement Time Msec,Page Title,Page Referrer
0,0001910c-deb5-5939-91c6-03a19323545a,2024-11-14 01:43:38.349527,2024-11-14 01:44:01.158066,14,2024,11,page_view,cf502e89-4289-4d96-8ca1-59c20dc73f3c,None,None,...,Port Washington,Americas,United States,Milwaukee WI,Wisconsin,Northern America,https://www.shopko.com/schedule-details/?store=,None,Schedule Details,https://www.shopko.com/schedule-appointments/
1,00039393-fea8-50c7-aa67-e81a179797ad,2024-11-13 19:34:31.738505,2024-11-13 19:47:14.606687,9,2024,11,first_visit,1b7dd312-6312-46bf-b783-b7cb2f2850eb,None,None,...,Wausau,Americas,United States,Wausau-Rhinelander WI,Wisconsin,Northern America,https://www.shopko.com/eye-care/,None,Eye Exam Center Locations Near You,None
2,0004a830-1702-5d3b-9831-055b03c84fe4,2024-11-14 03:23:55.364481,2024-11-14 03:24:00.384254,2,2024,11,link_click,9aadb733-1f9b-4164-9d78-16583b87a9f3,None,None,...,Los Angeles,Americas,United States,Los Angeles CA,California,Northern America,https://www.shopko.com/eye-care/sd/sioux-falls...,993.0,Vision Insurance in Sioux Falls West - Shopko ...,https://www.shopko.com/eye-care/sd/sioux-falls...
3,00058407-40f7-5164-909a-771cfa3035db,2024-11-13 17:38:17.629148,2024-11-13 17:38:28.254047,5,2024,11,first_visit,dc3c2686-0692-417c-b85e-54a61fb40815,None,None,...,Magna,Americas,United States,Salt Lake City UT,Utah,Northern America,https://www.shopko.com/eye-care/?utm_source=em...,None,Eye Exam Center Locations Near You,None
4,0007ea9f-b028-5a41-a4f0-4ddcc75c24aa,2024-11-13 16:38:30.996031,2024-11-13 16:38:38.782140,12,2024,11,page_view,63a89df5-ec01-4b2e-a7c5-a475a7aeaf2a,None,None,...,South Lyon,Americas,United States,Detroit MI,Michigan,Northern America,https://www.shopko.com/customer-service/,None,"Customer Service, Appointments, Returns & FAQ ...",https://www.shopko.com/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18488,fff577e3-3b22-52dd-b98e-4a4fe0fd7eea,2024-11-14 04:25:14.127726,2024-11-14 04:25:19.235001,8,2024,11,first_visit,fb24c201-2778-4a51-b48c-1e3e37a315c8,None,None,...,None,Americas,United States,Denver CO,Colorado,Northern America,https://www.shopko.com/eye-care/?utm_source=WB...,None,Eye Exam Center Locations Near You,None
18489,fff5cea6-464a-5cea-a960-1e8a59275e4e,2024-11-14 04:34:09.371270,2024-11-14 04:34:40.507648,12,2024,11,page_view,b3e56490-134c-4d9d-b0ff-fd25f2133fa1,None,None,...,Little Chute,Americas,United States,Green Bay-Appleton WI,Wisconsin,Northern America,https://www.shopko.com/frames/brands/oakley/?f...,None,Oakley | Shopko Optical,https://www.shopko.com/frames/?filter_sunglass...
18490,fff8f7c5-38b3-53d8-bdf5-9f4fd670fa96,2024-11-13 20:25:21.218212,2024-11-13 20:31:09.377112,18,2024,11,page_view,86e9101a-5c75-44cc-96d5-0b8ca5fbcfc8,None,None,...,Chicago,Americas,United States,Chicago IL,Illinois,Northern America,https://www.shopko.com/schedule-steps/?store=0...,None,Schedule Steps,https://www.shopko.com/schedule-exam/?store=02...
18491,fffeb2c6-02d6-594e-a320-a0b59ea2afe1,2024-11-13 20:12:00.527877,2024-11-13 20:12:11.185292,4,2024,11,page_view,fd1fadcf-5b7a-4286-8005-f8cfa6ed6864,None,None,...,Appleton,Americas,United States,Green Bay-Appleton WI,Wisconsin,Northern America,https://www.shopko.com/digital-eye-exams/,None,Digital Eye Exams | Shopko Optical,https://www.shopko.com/eye-care/wi/de-pere/sto...
18492,fffef4d8-ca54-5d1d-afa6-a05240ccba2f,2024-11-13 23:18:36.334284,2024-11-13 23:18:50.154299,13,2024,11,page_view,193f37d6-b1c8-4b83-bf3d-521b39f25def,None,None,...,Chicago,Americas,United States,Chicago IL,Illinois,Northern America,https://www.shopko.com/eyeglasses/lens-materials/,None,Lens Materials | Features and Benefits | Shopk...,https://www.shopko.com/eye-care/wi/janesville/...

In [10]:
events_df = build_table(df, mapping_rules, 'Events')
events_df

,event_timestamp,year,month,event_name,session_id,pageview_id,event_id,Device - Advertising ID,Device - Browser,Device - Browser Version,...,Tax,Event Classes,Event IDs,Event Text,Event Domains,Event Outcome,Percent Complete,Ecommerce,Items,Event URL
0,2024-11-14 05:54:51.907376,2024,11,first_visit,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,ca6c0d15-cff3-5e24-acf1-32a16e437eca,NaN,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None
1,2024-11-14 05:54:51.907376,2024,11,session_start,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,1d876485-58fe-50bc-9d35-d49102b5929f,NaN,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None
2,2024-11-14 05:54:51.907376,2024,11,page_view,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,ba318429-35c6-5e9b-97cf-5af73f23a361,NaN,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None
3,2024-11-14 05:54:57.126554,2024,11,user_session_info,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,30ef06d6-1cd0-508b-8cdc-b779fe8d33e6,NaN,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None
4,2024-11-14 05:55:08.384203,2024,11,scroll,56b4c156-3b3b-449f-8db0-18dfb3936d53,287c6512-bbc1-57df-b1a3-5dc9231b343a,7520f636-f1aa-5704-a018-8f352bf5ed34,NaN,NaN,NaN,...,None,None,None,None,None,None,10.0,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260859,2024-11-14 03:17:08.166826,2024,11,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,b3442476-472f-5b31-b138-decd75dc9029,NaN,NaN,NaN,...,None,None,None,None,None,None,20.0,None,None,None
260860,2024-11-14 03:17:26.457025,2024,11,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,f09b9137-56cb-5308-9ef7-0a6ea93884ee,NaN,NaN,NaN,...,None,None,None,None,None,None,30.0,None,None,None
260861,2024-11-14 03:17:26.457025,2024,11,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,f09b9137-56cb-5308-9ef7-0a6ea93884ee,NaN,NaN,NaN,...,None,None,None,None,None,None,40.0,None,None,None
260862,2024-11-14 03:17:45.807694,2024,11,scroll,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,cc8a8d6a-c437-5afe-8004-e240e592fda1,NaN,NaN,NaN,...,None,None,None,None,None,None,50.0,None,None,None
260863,2024-11-14 03:19:56.763039,2024,11,user_engagement,df966189-a01b-4b3c-abe7-7d6b5481a98c,13b92b7f-c488-5e1d-8bbb-b20e2a207607,95d57de2-cae7-58d9-93cb-1e771ac0aca7,NaN,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None

In [11]:
groupby_events = groupby_events(events_df)
groupby_events

,event_id,event_start_time,event_end_time,total_events,year,month,event_name,session_id,pageview_id,Device - Advertising ID,...,Tax,Event Classes,Event IDs,Event Text,Event Domains,Event Outcome,Percent Complete,Ecommerce,Items,Event URL
0,00000daf-91eb-5e95-bca1-c79290aa61c5,2024-11-13 13:23:35.170229,2024-11-13 13:23:35.170229,1,2024,11,Appointment_Scheduled_V2,4ffcadae-940e-4b67-9b0e-3d87ba781e43,7b0ef504-4a8f-5134-a683-777d30f2a126,None,...,None,None,None,None,None,None,None,None,None,None
1,0000938a-a58c-589e-95bd-2b69deef6684,2024-11-13 19:24:27.680993,2024-11-13 19:24:27.680993,1,2024,11,scroll,2c9fb154-a8a6-40b4-abfc-68f60eff1e42,51038003-5801-5180-b14d-e70daebf8653,None,...,None,None,None,None,None,None,80.0,None,None,None
2,00024406-b057-5e41-bec7-a2b07f5ded21,2024-11-14 01:25:08.623430,2024-11-14 01:25:08.623430,1,2024,11,page_view,a18fde4d-a303-4b3d-abee-74c595492a1f,7db1f63b-0b4e-5a69-9564-5f98b9568996,None,...,None,None,None,None,None,None,None,None,None,None
3,000248eb-d76c-5cea-a0ca-3369d32769e0,2024-11-14 01:21:03.720416,2024-11-14 01:21:03.720416,2,2024,11,link_click,240fbe79-665d-4930-b173-0f9734f3a652,886462c0-519c-5105-8d70-853615bf78a3,None,...,None,None,None,Women,None,None,None,None,None,https://www.shopko.com/frames/?filter_gender=w...
4,0002ccbe-4c12-5c90-8d2a-3ebaec5e9108,2024-11-13 20:57:43.080839,2024-11-13 20:57:43.080839,1,2024,11,scroll,95defd06-e8c8-4ee6-907a-16a3ae94aecd,ade68b84-ad74-5ee4-97d0-8fbfb84c99cc,None,...,None,None,None,None,None,None,10.0,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158813,fffeef63-1995-5f0e-bb9b-d1b4fc7cef79,2024-11-13 13:25:21.298013,2024-11-13 13:25:21.298013,1,2024,11,scroll,22c375fc-2f74-4a93-a1f0-c38160c1ba27,8208f7f6-8ba8-50b2-a85f-1ea3b92ec40e,None,...,None,None,None,None,None,None,60.0,None,None,None
158814,ffff35ee-d31f-5693-8328-d9dfaae3f9ff,2024-11-13 19:24:20.515748,2024-11-13 19:24:20.515748,1,2024,11,page_view,2a30e68c-7488-46e7-b107-36e644911031,b1d80510-7df8-572b-9d8f-8aeb31af7287,None,...,None,None,None,None,None,None,None,None,None,None
158815,ffff822a-f140-5bbf-8d56-04e8a547e97c,2024-11-13 19:39:42.750846,2024-11-13 19:39:42.750846,2,2024,11,scroll,0281b17f-00e2-4aaa-876d-35f9cafa02f4,c24775b0-466d-523d-8d65-266085c87877,None,...,None,None,None,None,None,None,10.0,None,None,None
158816,ffffc5c0-f4d7-5841-9fa3-20d3d332c42f,2024-11-13 19:32:50.745755,2024-11-13 19:32:50.745755,1,2024,11,user_session_info,bd102ba0-c4bc-411c-9a0c-77c7f3d0d643,000ee44d-d5b3-5fa8-913c-ad5ba483d50e,None,...,None,None,None,None,None,None,None,None,None,None
158817,ffffd5e9-7b4a-5d5f-963b-96ed67a05d38,2024-11-13 22:11:06.200422,2024-11-13 22:11:06.200422,1,2024,11,scroll,20e7812d-0da9-4776-891c-ee12e22668f6,22667fc0-e117-5da0-a147-10ea92a7fea0,None,...,None,None,None,None,None,None,30.0,None,None,None

In [12]:
end_time = time.time()
print(f"Total notebook execution time: {end_time - start_time:.2f} seconds")

Total notebook execution time: 21.85 seconds

Comparing a NumPy array to a scalar value is extremely fast and efficient, which is a major reason why it's a preferred method for creating boolean masks compared to looping through a pandas Series.

Vectorization
The core reason for this speed is vectorization. NumPy operations are implemented in a low-level, pre-compiled language like C or Fortran. When you write event_name_arr == "page_view", you aren't telling Python to iterate through the array element by element. Instead, you're triggering a highly optimized, single operation that performs the comparison on all elements of the array in parallel.  This is fundamentally different and much faster than Python's native for loops, which have significant overhead for each iteration.

The Result: A Boolean Mask
The result of this vectorized comparison is a boolean NumPy array of the same size as the original array. This array is called a boolean mask, where each element is True or False based on whether the corresponding element in event_name_arr matched the scalar value "page_view".